### ISSUE TITLE
Team Vetting : accès admin avec role/permissions ?

### ISSUE THREAD

**Issue by carsso** [hostolab/covidliste#163]
Il faudrait qu'on granularise les accès admin pour pouvoir donner accès a des portions du panel

La team vetting a besoin de donner accès en RO aux centres de vaccination et pouvoir ajouter des commentaires sur les centres existants. Tout le reste ne doit pas être modifiable.

@ssaunier Tu avais parlé d'un truc de permissions l'autre jour

**Comment by adrienpoly** [comment]
@carsso il y a un début d'implémentation de Pundit  avec ici https://github.com/hostolab/covidliste/issues/311 une issue qui  liste les ressources à couvrir par une policy

https://github.com/hostolab/covidliste/issues/311

Les deux PR listés dans cette issue donnent des exemples pour en ajouter
