### ISSUE TITLE
Replace address with zipcode in pending match confirmation view

### ISSUE THREAD

**Issue by colinemarie** [hostolab/covidliste#192]
- Replace full address details of the vaccination center with zipcode for pending match view
- Display full address details only in confirmed match view

https://github.com/hostolab/covidliste/blob/83c19aee43000e8918b742b6f258ce444afe9a8b/app/views/matches/_match_details.html.erb#L4-L6

**Comment by FelixMalfait** [comment]
Merci Coline !  Quelle est la motivation ? Les adresses des centres de vaccination sont en général publiques, non ? Un code postal c'est peu précis pour un volontaire qui voudrait s'y rendre, à Grenoble je peux mettre plus de 30minutes à pieds à traverser la ville (unique code postal)
