### ISSUE TITLE
[Partenaire] Création et suivi de campagne

### ISSUE THREAD

**Issue by cmozzati** [hostolab/covidliste#206]
Formulaire de création de campagne : https://invis.io/B310NWRJ6DWG#/449057737_covidliste_-_Partenaires_-_Form_01_-_Violet

Page suivi de campagne (à passer en violet) : https://invis.io/B310NWRJ6DWG#/449056870_covidliste_-_Partenaires_-_Suivi

**Comment by mininao** [comment]
Remplacé par #528
