### ISSUE TITLE
[Partenaire] Refonte du formulaire d'inscription

### ISSUE THREAD

**Issue by cmozzati** [hostolab/covidliste#207]
Maquette : https://invis.io/B310NWRJ6DWG#/449071520_Covidliste_-_Inscription_Partenaire

**Comment by multicolaure** [comment]
Bonjour, 

Je voudrais développer ce ticket, est-ce que quelqu'un peut m'assigner dessus ?

La maquette ne reprend pas exactement le thème de bootstrap visible sur les autres pages, notamment les champs de texte. Je compte garder le style existant pour que la page reste cohérente avec le reste. 

C'est ok pour vous ? @mininao / @cmozzati 
Merci

**Comment by multicolaure** [comment]
Voilà un aperçu d'une première version. J'ai essayé de respecter les couleurs du thème existant, et j'ai conservé le formulaire tel quel.

Si c'est ok pour vous, je pousse un PR. 

![Screenshot_2021-05-02 Devenez partenaires de Covidliste Desktop](https://user-images.githubusercontent.com/43094923/116815705-10fa1600-ab5f-11eb-9884-5a4a1b249497.png)
![Screenshot_2021-05-02 Devenez partenaires de Covidliste Mobile](https://user-images.githubusercontent.com/43094923/116815709-135c7000-ab5f-11eb-9c35-2bbde7ecaf91.png)
![Screenshot_2021-05-02 Devenez partenaires de Covidliste - dektop confirm](https://user-images.githubusercontent.com/43094923/116815713-15263380-ab5f-11eb-9998-d9177601acfa.png)
