### ISSUE TITLE
[Volontaire] Refonte du formulaire d'inscription

### ISSUE THREAD

**Issue by cmozzati** [hostolab/covidliste#208]
Maquette https://invis.io/B310NWRJ6DWG#/449068772_Covidliste_-_Inscription_Volontaire

**Comment by Bbemol** [comment]
Est-ce que quelqu'un travaille déjà sur l'intégration de ce design ? Un design system en cours ?

**Comment by navidemad** [comment]
Je veux bien attaquer le sujet si vous voulez

**Comment by Bbemol** [comment]
@navidemad je suis encore en train d'essayer de mettre en place mon environnement personnellement... J'ai pas mal de difficultés comme je connais pas trop ruby on rails, donc si tu veux attaquer tu peux et on se tient au courant. On peut même faire un discord si tu veux.

**Comment by navidemad** [comment]
@Bbemol J'essaye de voir si je peux faire un max avec le theming de bootstrap nativement avant de faire des overrides en scss sur des classes du layout pour le moment.

**Comment by navidemad** [comment]
@mathieuripert Si tu peux faire un tour sur les visuels voir si ca te va ?
J'ai commencé l'implémentation :
![screencapture-localhost-3000-2021-04-17-04_17_23](https://user-images.githubusercontent.com/6686865/115099108-19820800-9f34-11eb-81e9-c25d3612f8dc.png)

**Comment by mininao** [comment]
Remplacé par https://github.com/hostolab/covidliste/issues/514
