### ISSUE TITLE
Add the possibility to create batches based on zipcode and not km

### ISSUE THREAD

**Issue by colinemarie** [hostolab/covidliste#217]
Allow partners when creating a new campaign to target users not only based on km distance but also zipcode.

https://github.com/hostolab/covidliste/blob/eeba4743b8bf73b69eef4f30baa970dfd4efd0c1/app/models/vaccination_center.rb#L85-L94

**Comment by rchampourlier** [comment]
@LauriePremel @LucileCha pas sûr que ce soit toujours d'actualité ? Je la taggue "draft" et je vous laisse revoir quand vous pouvez

**Comment by mininao** [comment]
Ouais je pense même qu'on peut fermer.

**Comment by rchampourlier** [comment]
👌 merci @mininao
