### ISSUE TITLE
Gestion des Twilio::REST::RestError

### ISSUE THREAD

**Issue by ssaunier** [hostolab/covidliste#218]
Certains `Match` ne peuvent pas être envoyés par SMS correctement pour plusieurs raisons 👍 

- Le numéro de téléphone est "fake" (e.g. `06 06 06 06 06`)
- Le numéro de téléphone est un téléphone fixe (e.g. `01 .. .. .. ..`)
- Le numéro de téléphone n'est pas autorisé sur le plan Twilio (numéro étranger par exemple)

Le problème actuel est que le lendemain, ces `users` vont retomber dans les campagnes, sans plus de succès. Il faut flagger ces utilisateurs pour qu'ils ne soient plus pris en compte dans les campagnes futures (et eventuellement les notifier par mail en leur demandant de mettre à jour leur telephone portable pour être prévenus s'ils le souhaitent)

ℹ️ Lorsqu'on passera à Sendinblue, il faudra ajouter les exceptions de ce service.

**Comment by EmCousin** [comment]
@ssaunier @GuillaumeWrobel si personne n'est déjà en train de travailler dessus je veux bien m'en occuper.
L'utilisation d'une gem comme phonelib ou phony me semblerait pratique ici, sauf si vous préférez continuer avec une solution de contrôle maison ?

**Comment by yann120** [comment]
Should we close this issue if it is fixed ?

**Comment by mininao** [comment]
Je ferme l'issue comme on va changer de provider.
