### ISSUE TITLE
Faire une demande pour la réduction du temps de backup des données

### ISSUE THREAD

**Issue by Florto** [hostolab/covidliste#230]
Demander de conserver maximum 2 backups mensuels. Pas de changement pour la politique des daily et des hebdo.

**Comment by rchampourlier** [comment]
@Florto il a été demandé à Scalingo de ne conserver sur leur infra SecNumCloud que les 3 derniers backups mensuels. C'est actif depuis le 20/3. Est-ce ok ?

Je ferme l'issue, n'hésite pas à la rouvrir si besoin.
