### ISSUE TITLE
Amélioration de la saisie des mots de passe

### ISSUE THREAD

**Issue by MatthieuGariel** [hostolab/covidliste#241]
Des utilisateurs remontent s'être trompés lors de la saisie du mot de passe sur la home.
D'autres utilisateurs voient leur mot de passe non autorisé, ne connaissant pas le pattern demandé.
Et lors de la réinitialisation du mot de passe, certains remontent des difficultés afin de valider le nouveau mot de passe (j'investigue sans résultat pour l'instant).

Afin de prévenir que cela arrive, et aussi d'éviter l'envoi de mails et les demandes au support :
- peut-on doubler le champ de mot de passe sur la home avec un champ de confirmation ?
- définir le pattern du mot de passe & l'afficher sous le champ de saisie (éventuellement la puissance : faible, moyenne, forte)
- peut-on appliquer cela à la gestion des partenaires ?

**Comment by adrienpoly** [comment]
Aujourd'hui la seule contrainte sur le mot de passe est min 6 caractères (via devise). 

Je peux rajouter une partie JS pour afficher la validité du password si on est d'accord sur le format.

A mon avis c'est surtout coté partenaire/admin que le mot de passe doit être fort

**Comment by colinemarie** [comment]
@carsso  #229 y répond non ?

**Comment by carsso** [comment]
@colinemarie Pour la partie gestion des erreurs, maintenant oui. 
Par contre ça pourrait être bien de rendre le mot de passe un peu plus sécurisé par contrainte. A voir l'impact pour les gens.

**Comment by GuillaumeWrobel** [comment]
Que dites-vous d'un bouton « Afficher le mot de passe » comme celui-ci : 

@mathieuripert @carsso 

https://user-images.githubusercontent.com/20317297/114907871-cfa5fe80-9e1b-11eb-8322-e28b0dd32928.mp4
