### ISSUE TITLE
Ne pas demander nom/prénom au moment de l'inscription.

### ISSUE THREAD

**Issue by mathieuripert** [hostolab/covidliste#268]
Nouveau parcours utilisateur à mettre en place : 

 - [x] Ne pas récolter le nom et prénom à l’inscription.
 - [x] Enlever la possibilité de modifier nom/prénom sur l'espace `/profil`
 - [x] Ajouter une étape de récolte de nom et prénom au moment de l’acceptation du match.

**Comment by DavidLibeau** [comment]
Oui, d'une façon générale, on peut ne pas demander beaucoup des infos que CovidListe demande actuellement (je ferrais une issue avec d'autres idées). Pour moi, on peut remplacer le nom prénom dans le SMS par l'email partiellement anonymisé (en enlevant le domaine `Bonjour pseudo@o****.fr`  par exemple).

**Comment by Florto** [comment]
Dans le cas d’un exercice des droits, nous pourrions avoir besoin de l’information pour confirmer l’identité avant de procéder à la suppression, lorsque l’email utilisée n’est pas accessible, par exemple.

**Comment by carsso** [comment]
Le nom et le prénom, les centres l'utilisent pour savoir qui a un RDV et qui n'en a pas et pour vérifier les identités.
Si on le retire, ils vont devoir galérer à base d'identifiants autres (éventuellement un numéro d'identification ?) que potentiellement (pour les gros vaccinodromes) ils ne pourront pas entrer dans leur SI qui marche avec le nom et le prénom. Outre le fait que vérifier une identité avec un numéro d'identification, c'est pas dans leurs process, qui marche par identité réelle.

**Comment by mathieuripert** [comment]
Je ferme suite aux conclusions données ici #271

**Comment by Florto** [comment]
@mathieuripert peux-tu éditer ton message initial stp avec le contenu suivant : 

Réouverture de cette issue.

Nouveau parcours utilisateur à mettre en place : 
- [ ] Ne pas récolter le nom et prénom à l’inscription.
- [ ] Ajouter une étape de récolte de nom et prénom au moment de l’acceptation du match. Ne stocker l’info que dans le match

**Comment by navidemad** [comment]
On peut close l'issue la PR étant merge ?
