### ISSUE TITLE
Récolter le moins de données personelles possible

### ISSUE THREAD

**Issue by DavidLibeau** [hostolab/covidliste#271]
Comme l'indique #268, le nom et prénom pourrait ne pas être récolté. Je pense que d'autres information sont inutilement demandées par CovidListe.

CovidListe à besoin de l'âge des volontaires pour permettre de prioriser les notifications pour des personnes selon une catégorie d'âge définie. La date de naissance n'est pas utile. Seulement l'année de naissance permet, selon moi, d'avoir une données assez précise, à un an près.

L'issue #270 évoque l'adresse.

Le numéro de téléphone doit être facultatif. S'il permet pour de nombreuses personnes d'être alerter au plus vite, certaines autres personnes (moi par exemple ✋ ) n'utilisent que très peu les SMS voir ont carrément désactiver les notifications des SMS et sont beaucoup plus joignables par courriel. Le format français du téléphone discrimine également les personnes ayant un téléphone étranger mais vivant en France.

**Comment by mathieuripert** [comment]
Merci @DavidLibeau.
Ce sont des points intéressants.

**Date de naissance**
Il est tout à fait pertinent de ne demander que l’année de naissance.
En revanche il faudra arrondir l’âge à -1 pour éviter de matcher des personnes de moins de 18 ans, et à +1 pour les âges correspondant à des bornes inférieures de critères d’éligibilité. Example: on ne veut pas cibler une personne née en fin d’année 1966 pour une campagne 55+

**Numéro de Téléphone**
Le numéro de téléphone ne permet pas de valider l’inscription. Par ailleurs, lorsqu’une personne est « matchée » par un centre, un e-mail est également envoyé

**Comment by carsso** [comment]
Sur le sujet récoltes de données personnelles, mon avis perso est très simple : Il faut récolter uniquement ce dont on a besoin, mais sans être extrême dans la minimisation au point que ce soit ultra compliqué ou contraignant pour tout le monde. Dès le moment où on récolte 1 donnée perso, on doit gérer sa vie et sa protection donc quelques unes de plus c'est pas dramatique à mon sens. Par contre j'ai pas dit de se goinfrer comme certains (suivez mon regard...) ! 

Le nom et le prénom, les centres l'utilisent pour savoir qui a un RDV et qui n'en a pas et pour vérifier les identités.
Si on le retire, ils vont devoir galérer à base d'identifiants autres (éventuellement un numéro d'identification ?) que potentiellement (pour les gros vaccinodromes) ils ne pourront pas entrer dans leur SI qui marche avec le nom et le prénom. Outre le fait que vérifier une identité avec un numéro d'identification, c'est pas dans leurs process, qui marche par identité réelle.

L'âge, c'est encore pire. On avait réfléchi à un moment à approximer la date de naissance mais ça pose un gros problème selon moi. Etant donné qu'il est interdit par la DGS, pour certains vaccins, de vacciner les personnes en dehors d'une tranche d'âge, au jour près (aujourd'hui c'est 55+ mais demain ça pourrait être une range précise âge de début/âge de fin). En approximant les dates, on risque d'envoyer se faire vacciner des personnes qui sont hors de l'âge requis. Si une personne qui a donné la bonne date de naissance sur Covidliste, se retrouve convoquée à une vaccination et se fait injecter un vaccin interdit pour elle. Alors, oui, le centre sera probablement responsable, mais perso j'aurai pas la conscience tranquille, donc je m'y oppose fortement ! Seule alternative, si on arrondit, sacrifier 1 an de chaque côté de la range pour s'assurer qu'on envoie personne hors de l'âge minimum/maximum. Perso, en tant que personne, je préfère être inclus dans une vague de volontaires en autorisant la plateforme à garder ma date de naissance complète, plutôt que de risquer d'être exclus en leur donnant qu'une approximation !

L'adresse, comme tu l'as dit on l'a vu dans #270 

Le numéro de téléphone. Bon. Pour ça, j'ai un avis purement personnel assez tranché. Quand on donne les infos d'une personne a un centre avec un RDV, au delà de ceux qui entre les numéros dans leur SI pour booker le RDV, comment le centre fait pour la contacter en cas de pépin ? (Retard, etc). Les humains normaux dans la vraie vie utilisent leur téléphone, en tout cas la majorité. A partir du moment où de toute façon on a récolté des données on se doit de les traiter et de gérer leur cycle de vie. Ne pas prendre les numéros de téléphone c'est générer de l'emmerdement et de la frustration pour tout le monde. Et le rendre facultatif, c'est possible, je suis moyen chaud car la plus part des gens ne vont donc pas le remplir et ensuite venir nous dire que par mail ils peuvent pas réagir instantanément lors d'une proposition de RDV (c'est déjà le cas pour certains qui se sont trompés de numéro quand ils se sont inscrits). Pour les numéros internationaux c'est un bon point, je pensais qu'on les gérait, il va falloir qu'on regarde.

**Comment by Florto** [comment]
Du coup suite à lecture de l’analyse, la date de naissance et le numéro de téléphone se justifient complètement dans notre traitement et respectent l’objectif de frugalité.

Je propose cloture de cette issue.

**Comment by DavidLibeau** [comment]
@carsso Merci pour avoir pris le temps de donner des arguments.

Sur l'âge, je pense qu'on touche justement à un point crucial de conception. Et, encore une fois, je regrette que l'issue soit aussi rapidement fermée.

L'administration de vaccin est un acte médical qui est régit pas une éthique médicale. Selon moi, un système informatique conçu par des informaticien·ne·s ne doit pas se substituer à l'avis médical. Récemment, le vaccin AstraZeneca a été proscrit dans certaines régions : https://www.lemonde.fr/planete/article/2021/04/09/covid-19-en-france-l-utilisation-du-vaccin-d-astrazeneca-proscrite-en-moselle-en-guyane-a-mayotte-et-a-la-reunion_6076244_3244.html. Par conséquent, et selon votre point de vu, il faudrait alors que CovidListe vérifie qu'aucune dose de vaccin AstraZeneca ne soit distribuée via CovidListe pour ces régions ? Plus généralement, est-ce que CovidListe doit prendre la responsabilité de contrôler le type de vaccin, l'âge et pourquoi pas la première dose reçue (date et type) ?

Je pense que ce n'est pas la responsabilité de CovidListe de vérifier ces informations. J'estime que les volontaires et les centres de vaccinationsont responsables des données qu'ils renseignent. A cet égart, il suffit de ne pas demander l'année de naissance mais simplement l'âge du volontaire dans le formulaire d'inscription. Pourtant, cette éventualité n'a pas pu être étudié puisque l'issue est déjà close. Dommage…

**Comment by carsso** [comment]
@DavidLibeau Oui, je suis d'accord, on ne se substitue pas au personnel médical et leurs vérifications.
Je suis pour qu'on fasse le maximum, de bonne foi, avec que ce qu'on à pour être précis dans le respect les critères donnés par les centres.
L'âge est directement lié a la date de naissance. Si on aproxime la date, on ne fait plus aussi bien. Soit c'est trompeur pour le centre, soit discriminant pour les gens (en fonction de la stratégie d'arrondi). En calculant un âge précis, si y'a une erreur, je suis droit dans mes bottes et je dors tranquille vu que ça vient pas de nous.

**Comment by DavidLibeau** [comment]
Comme je l'ai dit, on peut être précis en demandant l'âge au volontaire. Et comme nous sommes d'accord pour que le logiciel ne se substitue pas au personnel médical, c'est à eux, comme aux volontaires, de vérifier s'ils respectent les préconisations. Cela vaut aussi sur leur possibilité de se rendre au centre. Cela rejoint l'issue #270. En n'ayant qu'une seule adresse (sûrement de domicile), votre système est également imprécis et peut notifier des personnes qui sont en réalité loin du centre et plus près d'un autre centre. Mon point de vu est que ça doit être aux volontaires de décider et aux centres de sélectionner.

**Comment by mathieuripert** [comment]
@DavidLibeau 

Je ne vois pas comment on peut être précis en demandant uniquement l'âge.

Si une personne vous dit "j'ai 54 ans" aujourd'hui le 11 avril 2021, à quel moment pouvez l'inclure dans les critères d'éligibilité de vaccin 55+ ? Au mieux, qu'à partir du 10 avril 2022. 

Autrement dit, en demandant l'âge, vous ne faites pas mieux qu'en demandant uniquement l'année. 
Et comme énoncé plus haut ce n'est pas suffisamment afin que les centres de vaccination puissent parfaitement respecter le calendrier vaccinal et que les gens puissent obtenir leur vaccin le + tôt possible.
