### ISSUE TITLE
Décentraliser CovidListe 🤯 

### ISSUE THREAD

**Issue by DavidLibeau** [hostolab/covidliste#272]
La conception centralisée de CovidListe comporte de nombreux défauts. En constituant une base de données centralisée dans un cadre sanitaire, cela fait porter une lourde responsabilité sur les administrateurs de CovidListe. Une telle concentration de données augmente le risque d'être une cible de piratage. Accepter de stocker ses données personnelles par un unique acteur (non-institutionnel) peut être rebutant pour certaines personnes. Avoir un système de sélection qui comporte des défauts ou failles peut également réduire la confiance dans le système.

Il est proposé de décentraliser CovidListe. L'idée (de façon ultime) est de faire héberger CovidListe par les centres de vaccination (ou par un acteur tier, par exemple institutionnel). CovidListe du côté des centres de vaccination sera uniquement le diffuseur et le sélectionneur de volontaires. Il diffusera sa campagne et permettra à tout-un-chacun de s'inscrire (via une API ou un formulaire), puis ferra sa sélection comme il l'entend (et donc sous sa responsabilité).
Dans cette version de CovidListe, il ne sera plus forcément nécessaire d'avoir une base de données centralisée des volontaires. Chaque volontaire pourra recevoir les campagnes selon leur choix et postuler en un clic (ou même automatiquement) à ces campagnes. Les données personnelles nécessaires seront stocker en local sur son application mobile CovidListe, par exemple.

Nous pouvons aller vers la décentralisation de façon progressive. La première étape est de séparer le plus possible le côté centre de vaccination et le côté volontaires. Puis de créer une API côté centres. Et ensuite de travailler sur l'hébergement.

**Comment by Florto** [comment]
La solution décentralisée implique un hébergement à la charge des vaccinateurs, ce qui est irréaliste.

En plus de leur apporter une charge supplémentaire de travail, ce qui va à l’encontre de cette initiative qui a pour objectif de leur apporter une solution clé en main.

D’un point de vue privacy, la difficulté que représente la maintenance et la mise à jour d’une plateforme installée à de nombreux endroits et l’augmentation des flux réseaux augmente les risques autour de la fuite de données.

**Comment by carsso** [comment]
@DavidLibeau
Je rejoins @Florto 
Les centres n'ont absolument pas les moyens, ni techniques, ni humains, pour opérer une plateforme (sauf peut-être quelques très très gros).
Quand on parle de "centre", on parle aussi bien du Stade de France, que de la petite pharmacie du quartier qui vaccine < 10 personnes par jour (il va falloir qu'on change les mots qu'on utilise, car la notion de "centre" fait uniquement penser aux gros Vaccinodromes).

Effectivement, peut-être que l'Etat pourrait héberger, de manière centralisée. Ça me parait moins irréaliste que de faire une plateforme décentralisée.
Si les services de l'Etat veulent nous fournir la plateforme d'hébergement pour dissiper les craintes, ils ont les moyens de nous contacter pour qu'on discute.
Mais pour l'instant à ma connaissance, personne ne nous a approché en ce sens.

**Comment by Florto** [comment]
Je propose la cloture de cette issue.

**Comment by carsso** [comment]
Yep, pour moi c'est good @Florto

**Comment by DavidLibeau** [comment]
Les arguments que vous donnez sont bons. Je précise toutefois que l'hébergement peut être fait par d'autres acteurs tiers (y compris institutionnels ou associatifs).
Cependant, cette issue porte davantage sur la conception de l'outil que de l'hébergement.

Concevoir un outil décentralisé permet sa réutilisation et son interopérabilité (si vous voulez que je renomme l'issue "rendre CovidListe interopérable, je serais 100% partant). En restant sur un outil centralisé, certains acteurs pourraient refuser d'y souscrire pour différente raisons (notamment le partage d'informations de santé). Cela pousse aussi la concurrence des outils (on a déjà vu la mise en place d'un concurrent à CovidListe par Medicamentum). En permettant l'interopérabilité, les partenaires pourraient être indépendants. Je pense que cette possibilité pourrait accroitre l'acceptabilité du logiciel.

**Comment by Florto** [comment]
Le processus d’intégration des partenaires implique de nombreuses interventions humaines.

À moins d’être particulièrement complexe et hors de propos dans notre démarche au moins aujourd’hui, la solution que vous proposez impliquerait de proposer à n’importe qui de déclencher une campagne, ce qui est dangereux et absurde.

Je rappelle que nous sommes ici pour proposer une solution simple, clé en main, pour répondre à une problématique immédiate.

**Comment by mathieuripert** [comment]
@DavidLibeau 
Peux tu nous préciser en quoi un outil décentralisé faciliterait sa réutilisation ? 
Est ce du côté « partenaires » ou « volontaires » que le problème de l’acceptabilité se pose selon toi ?
Et quoi la concurrence des outils est une mauvaise chose ?

**Comment by DavidLibeau** [comment]
@Florto Je trouve dommage d'avoir clôturé cette issue aussi rapidement.

> la solution que vous proposez impliquerait de proposer à n’importe qui de déclencher une campagne

Je propose pas cela mais si pas "n'importe qui" vous considérez que tous les pharmaciens, les vétérinaires, les dentistes (qui peuvent vacciner) devrait pouvoir déclencher une campagne, alors oui, en effet, ce sont bien des personnes ayant potentiellement des doses à administrer. Et c'est d'ailleurs un des points que CovidListe va devoir traiter : comment vérifier-t-elle l'identité et la qualification des partenaires qui s'inscrivent ?

@mathieuripert 
Aujourd'hui, si l'Etat (par exemple) veut mettre en place cet outil, il peut déployer le code source, mais sans la base de données, c'est inutile. Demain, avec un outil interopérable, ce que l'Etat pourra déployer c'est le côté partenaire (la gestion des campagnes, de la sélection et de l'API pour postuler). Avec une service décentralisé, les clients pourront être nombreux, CovidListe avec sa bdd à 500k mais aussi d'autres acteurs et possiblement des solutions indépendante auto-hébergés.
Avec un système décentralisé, je vois des bénéfices sur l'acceptabilité des deux côtés : 
Côté partenaires : 
- ceux-ci ne vont pas avoir a réserver leurs données et leur doses à un seul acteur (ce qui pourrait d'ailleurs leur poser des problèmes, surtout pour les acteurs publics); 
- ils vont pouvoir être indépendant et même (certes je le conçois dans un futur plutôt lointain) de pouvoir faire une sélection totalement personnalisée, s'il le veulent.

Côté volontaires : 
- en permettant l’interopérabilité, on permet aussi la naissance de solutions qui correspondent plus à ce que certains volontaires acceptent. Par exemple, on pourrait être vraiment partant pour un système d'inscription mais ne pas accepter l'algorithme de sélection ou l'enregistrement de données perso par un intermédiaire (par CovidListe). Avec une API qui publie les disponibilités de doses et une pour la réception des candidatures, moi perso, ça me prend que quelques heures pour faire un site qui check les disponibilités et qui envoi des candidatures mais en ayant mes données uniquement stockées en local. Cela permettra aussi à des outils comme [ViteMaDose](https://github.com/CovidTrackerFr/vitemadose).
- pour finir, et comme le l'évoque ici https://twitter.com/DavidLibeau/status/1380423460221034496 un système décentralisé peut aussi permettre d'augmenter l'accessibilité puisque le système peut enregistrer davantage de paramètres (notamment des paramètres déclaratifs sur les possibles handicaps) puisque ceux-ci seront stockés sur des infrastructures des centres de vaccination.

La concurrence des outils centralisés est une mauvaise chose car cela va forcer les usagers à partager leur données avec beaucoup d'intermédiaires (beaucoup de CovidListe like) et fracturer les listes d'attente. Sans système interopérable, les centres de vaccination ne vont pas pouvoir être sur deux systèmes à la fois. Cela va réduire aussi pour CovidListe la possibilité d'offrir des doses pour des centres qui ne pourront pas être sur deux systèmes et qui auront potentiellement choisi un autre système.

**Comment by carsso** [comment]
@DavidLibeau 
Attention interopérable et décentralisé c'est complètement différent !

Pour l'interopérabilité on pourrait très bien fournir les accès aux centres sous forme d'API. Mais aujourd'hui c'est pas ce qu'ils veulent, la preuve qu'ils ont pas les ressources pour faire du dev même sur une API simple. Ils nous demandent des Excel (on fournit des CSV du coup) qu'ils importent de leur coté dans leurs outils (doctolib ou autre) ou qu'ils traitent et formatent tel quel.

Concernant la décentralisation : 
Côté volontaires : Objectivement, tu vas avoir 3 clampins qui vont l'utiliser en déployant leur version, tous les autres vont aller se centraliser sur une grosse instance, ce qui revient au même. Je vais pas cracher sur eux, ce sont de belles initiatives sur le papier et c'est cool que ça existe, mais on voit bien ce que ça donne avec Peertube ou Mastodon. Y'a pratiquement personne dessus, la plus part des gens sont sur leur équivalent centralisé, et les quelques rebelles qui y sont sont presque tous agglutinés sur 2-3 énormes instances (et beaucoup font du crosspost sur la plateforme centralisée, c'te blague...).
Côté centres, va trouver, ne serais-ce que 10 gros centres (>500 doses/j) qui sont chauds pour qu'on le fasse décentralisé et hosté chez eux, prêts à le maintenir. C'est pas réaliste. Et quid des petits ? Il ont pas les serveurs, pas les connaissances, pas les gens.

En tout cas, si ça doit se faire, des deux côtés ça va demander un travail de MALADE qui va durer des semaines voir des mois pour le dev, le maintien et tout ça, alors que si ça se trouve dans 3 mois tout le monde est vacciné, on est sauvés et on peut fermer. Donc je suis pas pour.

**Comment by DavidLibeau** [comment]
Oui, interopérabilité et décentralisation sont différentes, mais l'interopérabilité est nécessaire pour la décentralisation.

> Pour l'interopérabilité on pourrait très bien fournir les accès aux centres sous forme d'API. 

C'est exactement ce que je demande mais surtout pour les volontaires.

> En tout cas, si ça doit se faire, des deux côtés ça va demander un travail de MALADE qui va durer des semaines voir des mois pour le dev

Je ne suis pas d'accord. Comme je l'ai dit, au niveau du code, il ne suffit que de scinder la partie centre de vaccination et la partie volontaire, avec une communication par API. C'est pas si compliqué, mais je conçois qu'une architecture par sous-projet de base aurait été bien plus simple à réaliser que de faire une division maintenant. C'est pour cela que j'ai appelé depuis plusieurs jours à ce débat…

Votre lecture de l'histoire des systèmes décentralisés est la votre et je n'y souscris pas. Mastodon et PeerTube correspondent à des alternatives décentralisés de système monopolistiques. Ce ne sont pas les seuls exemples de systèmes décentralisés. Le web comme le mail est décentralisé et fonctionne très bien ainsi. CovidListe quand à lui choisit également la voie monopolistique et c'est bien de l'assumer comme vous le faites, même si je le déplore (pour toutes les raisons précédement citées).

Je déplore aussi que cette issue ait été aussi rapidement close. On voit très bien que le débat est utile. En la fermant aussi vite et de façon autoritaire comme vous l'avez fait avec mes autres issues, vous réduisez la possibilité aux autres continuteur·rice·s de participer à l'élaboration de la vision et des objectifs de CovidListe. C'est dommage.

**Comment by carsso** [comment]
Si tu te chauffes et que tu fais une PR pour découper le projet en deux avec une API on pourra regarder.
Attention a ce que ce soit bien compatible avec le standard Heroku (c'est ce que utilise Scalingo)

**Comment by DavidLibeau** [comment]
L'issue a été fermée en 34 minutes (temps entre le premier retour et la clôture). Ainsi, je ne vais pas m'aventurer à passer du temps sur une fonctionnalité qui a déjà été rejetée en bloc.

**Comment by Florto** [comment]
Je réitère, j’ai l’impression que vous souhaitez en fait que covidliste soit un autre logiciel. Il vous est tout à fait possible de le développer ce nouveau logiciel, basé sur celui-ci ou pas. 

L’issue a été fermée, car 4 personnes ont considéré qu’elle ne s’intègre pas au backlog et à la vision portée pour le produit aujourd’hui. 
Je vous laisse prendre note que l’une des issues que vous avez soumise est, elle, toujours ouverte, car amène une question qui conduit à une réflexion.

Je reste toujours disponible sur florto.covidliste@gmail.com pour échanger autour de tout ça.
