### ISSUE TITLE
Clarifier tous les partenaires de CovidListe

### ISSUE THREAD

**Issue by DavidLibeau** [hostolab/covidliste#273]
CovidListe transmet des données à des tiers sans les mentionner dans sa politique de confidentialité.

Par exemple, Algolia et api.gouv.fr sont utilisés pour le géocodage (c.f. #5 & https://github.com/hostolab/covidliste/blob/master/app/services/geocoding_service.rb).

Les centres de vaccinations partenaires devraient également être listés pour d'avantage de transparence.

**Comment by Florto** [comment]
Les centres de vaccinations sont précisés de façon générique dans la notice relative à la protection des données.

La publication des partenaires nominative est aujourd’hui soumis à l’accord du responsable du partenaire concerné.

Les données transmises au tiers sont des données atomiques qu’il n’est pas possible de recroiser, strictement nécessaires pour le bon fonctionnement de la plateforme.

**Comment by DavidLibeau** [comment]
Algolia récupère toutes les adresses postales entrées dans le formulaire d'inscription tout en sachant qu'elles proviennent de CovidListe car une identification est requise.

**Comment by Florto** [comment]
Cela n'entre pas en contradiction avec le fait que c'est une donnée atomique impossible à recroiser.

**Comment by DavidLibeau** [comment]
Une adresse postale peut être croisée avec beaucoup de base de données. Mais le principal point de vigilance pour moi n'est pas le croisement mais l'utilisation pour prospection commerciale. Je ne connais pas la politique d'Algolia mais c'est techniquement possible.
Ici c'est aussi au niveau du traitement des données des adresses qui n'est pas déclaré dans la politique de confidentialité de CovidListe.

**Comment by Florto** [comment]
Effectivement, je comprends, il est dangereux que aloglia soit au courant qu'une adresse postale existe.

Bref, le sujet est en cours d'analyse, affaire à suivre.
