### ISSUE TITLE
Réduire le temps de conservation des données des personnes matchées à 24h.

### ISSUE THREAD

**Issue by Florto** [hostolab/covidliste#275]
Prérequis : Changer le process d’analyse des matchs buggés

- [ ] Mettre en œuvre la procédure (manuelle ou automatisée) de restauration d’environnement
- [ ] Avoir le temps de l’appliquer considérant que faire ces investigations impacte la capacité de développement et correction de bugs

**Comment by DavidLibeau** [comment]
Le Conseil d'Etat considère comme acceptable la conservation pour 3 mois des données de rendez-vous de vaccination selon https://www.conseil-etat.fr/fr/arianeweb/CE/decision/2021-03-12/450163. Une information peut-être intéressante pour CovidListe. A voir si cela est pertinent ici.

**Comment by mininao** [comment]
Je me permet de mettre ça en P3 dans le sens où je crois qu'on est pas prêts vu qu'on fait encore pas mal de debug.
