### ISSUE TITLE
Rendre le numéro de téléphone "User-friendly" dans les formulaires et les vues

### ISSUE THREAD

**Issue by carsso** [hostolab/covidliste#278]
Le format du numéro qu'on utilise dans le profil est perturbant pour les gens,
> Je suis étonné de découvrir que mon numéro de téléphone dans mon profil est préfixé par "336" au lieu de "06".
Ils pensent que c'est buggué et qu'on arrivera pas a les contacter

Suggestion de @ssaunier 
> Codons une methode « human_friendly_phone_number » dans le modèle User, et fans ue UsersControllers#show on fait un @user.phone_number = @user.human_friendly_phone_number

**Comment by hack3rvaillant** [comment]
👋🏾 J'ai une PR #297 ouverte sur cette issue
