### ISSUE TITLE
Contrainte/Warning age minimum 55 sur les campagnes AZ 

### ISSUE THREAD

**Issue by mathieuripert** [hostolab/covidliste#281]
Ajouter une contrainte supplémentaire sur l’âge minimum (55 ans minimum) pour les campagnes AstraZeneca.

**UPDATE**
Ajouter un message de "warning" lorsqu'un partenaire décide de lancer une campagne AZ avec un age minimum < 55. Mais ne pas empêcher la création de la campagne.

**Comment by DavidLibeau** [comment]
Est-ce que vous allez aussi interdire les campagnes AstraZeneca dans les régions citées ici : https://www.lemonde.fr/planete/article/2021/04/09/covid-19-en-france-l-utilisation-du-vaccin-d-astrazeneca-proscrite-en-moselle-en-guyane-a-mayotte-et-a-la-reunion_6076244_3244.html ?

**Comment by Florto** [comment]
Il ne me semble pas pertinent de mettre ce genre de contrainte, en effet pour moi c'est au vaccinateur qui crée sa campagne de décider celà, notre solution devrait être agnostique au type de vaccin (même si on a précodé les différents types de vaccins dans le formulaire).

**Comment by DavidLibeau** [comment]
@Florto Quid des personnes ayant reçu une dose d'un vaccin A et dont la campagne porte sur un vaccin B ?

**Comment by Florto** [comment]
Qu'est ce que votre remarque a à voir avec le sujet ?

**Comment by DavidLibeau** [comment]
Oui, les deux correspondent à une contrainte concernant la sélection des personnes à notifier.

**Comment by Florto** [comment]
La question est de savoir si le logiciel doit forcer la limite à 55 ans pour le vaccin AZ.
Je repose ma question, qu'est ce que la prise en compte du cas des AZ de moins de 55 ans qui voudraient avoir une deuxième dose pas AZ a à voir ?

Sachant que tout primo vacciné a une priorité absolue pour recevoir sa deuxième en respect des schémas vaccinaux...


Ainsi certaines gens, faisant les empressés,
            S'introduisent dans les affaires :
            Ils font partout les nécessaires...

**Comment by DavidLibeau** [comment]
La question est plus générale : le logiciel doit-il prendre des décisions suivant la politique sanitaire française ?

**Comment by Florto** [comment]
Mais ce n'est pas le sujet de cette issue.

Dites "le logiciel doit-il prendre des décisions suivant la politique sanitaire" c'est dans le sujet.

Ce que vous dites dans votre remarque initiale est hors-sujet,mercide votre vigilance pour permettrede conserverla clartéde ces issues.

**Comment by mathieuripert** [comment]
> Il ne me semble pas pertinent de mettre ce genre de contrainte, en effet pour moi c'est au vaccinateur qui crée sa campagne de décider celà, notre solution devrait être agnostique au type de vaccin (même si on a précodé les différents types de vaccins dans le formulaire).



> Il ne me semble pas pertinent de mettre ce genre de contrainte, en effet pour moi c'est au vaccinateur qui crée sa campagne de décider celà, notre solution devrait être agnostique au type de vaccin (même si on a précodé les différents types de vaccins dans le formulaire).

C'est une remontée qui a été faite côté "supply". Mais effectivement on pourrait laisser "full control" au vaccinateur dans ses critères de campagne. Sur ce point là, l'idée c'est de mettre des "guardrails" pour éviter des erreurs. Ou alors au moins on pourrait imaginer un warning que le vaccinateur peut décider de ne pas suivre

**Comment by carsso** [comment]
Ouais, le warning c'est bien, quand on a une info, guider les gens c'est bien. Imposer/prendre la décision a leur place vaut mieux pas que ce soit de notre responsabilité (surtout si jamais demain la DGS change la politique)

**Comment by Florto** [comment]
Le warning c'est bien par contre ça nous augmente le niveau de dépendance entre les consignes sanitaires et la maintenance !

**Comment by mathieuripert** [comment]
Good point. C'est pas nécessaire. Vous m'avez convaincu ! Je ferme l'issue et on fera remonter côté supply

**Comment by DavidLibeau** [comment]
Je suis d'accord que cette fonctionnalité peut être intéressante, notamment pour éviter les erreurs, comme vous l'avez souligné, mais que cela implique l'intégration de beaucoup de paramètres (d'où mon point originel) et en plus cela engage la responsabilité de CovidListe (on peut aussi faire des erreurs et bloquer inutilement des doses par exemple)…
