### ISSUE TITLE
Permettre aux partenaires inscrits de recommander Covidliste à leurs confrères

### ISSUE THREAD

**Issue by ElBulgaro** [hostolab/covidliste#285]
A l'instar de l'ajout de l'URL avec paramètres de pré-remplissage du partage qui permet aux volontaires inscrits de recommander Covidliste sur Twitter, je propose la même chose pour les partenaires mais par email :

Voici un lien mailto avec les paramètres remplis généré par https://mailtolink.me/

[Cliquez ici pour recommander Covidliste à vos confrères](mailto:?cc=partenaires@covidliste.com&subject=Je%20vous%20recommande%20Covidliste%20pour%20trouver%20des%20volontaires%20%C3%A0%20la%20vaccination&body=Bonjour%2C%0D%0A%0D%0AJe%20viens%20de%20m'inscrire%20sur%20Covidliste%20pour%20r%C3%A9f%C3%A9rencer%20%22%7B%7Bnom%20du%20centre%7D%7D%22%2C%20ce%20qui%20permet%20d'utiliser%20la%20plateforme%20pour%20contacter%20les%20volontaires%20%C3%A0%20la%20vaccination%20en%20cas%20de%20doses%20de%20vaccin%20surnum%C3%A9raires.%0D%0A%0D%0AVoici%20l'adresse%20pour%20s'inscrire%20%3A%20https%3A%2F%2Fwww.covidliste.com%2Fpartenaires%2F%0D%0A%0D%0AJ'ai%20ajout%C3%A9%20l'%C3%A9quipe%20de%20Covidliste%20en%20copie%20en%20cas%20de%20question%20-%20le%20support%20est%20plut%C3%B4t%20r%C3%A9actif.%0D%0A%0D%0A%0D%0ACordialement%2C%0D%0A%7B%7Bpr%C3%A9nom%20%2B%20nom%7D%7D)

Je propose également que soit rempli de manière dynamique le prénom et nom du partenaire inscrit ainsi que le nom du centre, pour apporter plus de crédibilité à la demande.

Petite subtilité : l'adresse de contact dédiée au partenaire est ajouté en copie pour faciliter la reprise en main par l'équipe support.

**Le code** 

`mailto:?cc=partenaires@covidliste.com&subject=Je%20vous%20recommande%20Covidliste%20pour%20trouver%20des%20volontaires%20%C3%A0%20la%20vaccination&body=Bonjour%2C%0D%0A%0D%0AJe%20viens%20de%20m'inscrire%20sur%20Covidliste%20pour%20r%C3%A9f%C3%A9rencer%20%22%7B%7Bnom%20du%20centre%7D%7D%22%2C%20ce%20qui%20permet%20d'utiliser%20la%20plateforme%20pour%20contacter%20les%20volontaires%20%C3%A0%20la%20vaccination%20en%20cas%20de%20doses%20de%20vaccin%20surnum%C3%A9raires.%0D%0A%0D%0AVoici%20l'adresse%20pour%20s'inscrire%20%3A%20https%3A%2F%2Fwww.covidliste.com%2Fpartenaires%2F%0D%0A%0D%0AJ'ai%20ajout%C3%A9%20l'%C3%A9quipe%20de%20Covidliste%20en%20copie%20en%20cas%20de%20question%20-%20le%20support%20est%20plut%C3%B4t%20r%C3%A9actif.%0D%0A%0D%0A%0D%0ACordialement%2C%0D%0A%7B%7Bpr%C3%A9nom%20%2B%20nom%7D%7D`

**Comment by carsso** [comment]
Pas grand monde a un client mail en 2021, ou un navigateur configuré correctement pour le mailto:  je propose de mettre en dessous du bouton un textarea avec un contenu de mail tout prêt a copy/paste.

**Comment by carsso** [comment]
Il faut qu'on travaille le contenu avant d'implémenter tel quel.
Y'a des choses qu'on ne peut pas dire a la place des gens, genre "le support est plutôt réactif."
