### ISSUE TITLE
Mise à jour de NodeJS à prévoir

### ISSUE THREAD

**Issue by thbar** [hostolab/covidliste#289]
Ticket qui fait suite à https://github.com/hostolab/covidliste/pull/288.

J'ai cherché à comprendre quelle version de NodeJS s'applique en production (surtout pour éviter d'avoir des décalages entre le dév/test et la production), je note ce que j'ai trouvé ici.

Par défaut (voir https://doc.scalingo.com/languages/ruby/rails/start#specifying-a-custom-nodejs-runtime), il semble qu'en production l'application tourne probablement avec la version 10.15.3, qui date ([voir table des releases](https://nodejs.org/en/download/releases/)) de 2019-03-05.

Si vous êtes OK, on pourrait préparer une PR qui [spécifie la version via le BuildPack nodejs](https://doc.scalingo.com/languages/ruby/rails/start#specifying-a-custom-nodejs-runtime), et mettre à jour pour être sur la dernière version LTS (à discuter !).

**Comment by ssaunier** [comment]
Yes très cool 👌 - Je n'ai pas encore joué avec les buildpacks sur Scalingo, je pense que c'est comme Heroku. On a la possibilité de faire des "Review Apps" pour pousser des branches et tester avant un merge. 

PR Welcome ! 🙏
