### ISSUE TITLE
Envoyer un mail aux volontaires après vaccination. (Brancher le MatchMailer#send_anonymisation_notice au cron job)

### ISSUE THREAD

**Issue by ssaunier** [hostolab/covidliste#300]
cf:

- #248
- #197

**Comment by mininao** [comment]
Précisions :
* On veut envoyer un mail aux volontaires après vaccination pour les remercier et leur dire qu'on va anonymiser leur données
* Le mailer existe
* Il faut que dans le cronjob on appelle le mailer
* Il faut checker le contenu du mail, voir entre autres si on dit bien que le délai d'anonymisation et de 7j et non pas 24h

**Comment by yann120** [comment]
Hello 👋
I would like to work on this issue if possible 👍🏻

**Comment by Florto** [comment]
Je me permets une précision.

Je préférerais que le wording du mail dise « nous avons bien supprimé vos données. À des fins statistiques, comme prévu par nos CGU, des informations anonymisées ne permettant pas de vous identifier peuvent-être conservées. » plutôt que « nous allons anonymiser vos données »

**Comment by yann120** [comment]
> Je me permets une précision.
> 
> Je préférerais que le wording du mail dise « nous avons bien supprimé vos données. À des fins statistiques, comme prévu par nos CGU, des informations anonymisées ne permettant ni de vous identifier ni de vous contacter peuvent-être conservées. » plutôt que « nous allons anonymiser vos données »

J'imagine que ça inclue qu'il faudrait changer la feature d'anonymisation ?

**Comment by mininao** [comment]
> J'imagine que ça inclue qu'il faudrait changer la feature d'anonymisation ?

Non c'est juste un rewording du mail je pense !
Hésite pas à faire une PR @yann120, on ajustera le contenu du mail ensemble dans la PR si besoin si ça te va ? cc @Florto

**Comment by Florto** [comment]
Absolument, juste le wording😁

**Comment by yann120** [comment]
ok très bien! 👍

**Comment by rchampourlier** [comment]
J'ai l'impression que c'est implémenté par #550 donc je ferme. @Florto je te laisse rouvrir si je me trompe.

**Comment by yann120** [comment]
@rchampourlier oui c'est géré par #550 mais j'ai pas la main pour changer le statut de l'issue 🙂

**Comment by rchampourlier** [comment]
Merci @yann120 pour le retour, je ferme l'issue !
