### ISSUE TITLE
Différencier le rôle admin en plusieurs rôles

### ISSUE THREAD

**Issue by mathieuripert** [hostolab/covidliste#305]
# Contexte

Pour le moment nous avons qu'un seul rôle `:admin` qui permet d'avoir accès à l'interface admin. En revanche certaines personnes n'ont pas nécessairement besoin d'avoir toutes les mêmes permissions

# Suggestion

"Splitter" le rôle `:admin` en  plusieurs rôles:

- `admin` qui donne accès à tout l'interface admin
- `supply_admin` qui donne accès à la partie validation des centres partenaires
- `supply_member` qui donne accès à la partie supply en read only pour accompagner les centres (permissions à définir)
- `ds_admin` (`ds` = `data_science`) pour l'accès à Blazer
-  `dev_tools_admin` qui donne accès à pghero, flipper, sidekiq
- `support_admin` qui donne accès à des tools de support client (ex: recherche/suppression de compte par ex)

Il est tout a fait possible pour une personne de cumuler plusieurs roles.

@ssaunier @Florto @carsso @rchampourlier  Thoughts ?

Par ailleurs, c'est surement l'occasion de mettre en place la gestion de permissions via pundit (notamment sur la partie supply pour définir différentes permissions sur les resources)

**Comment by carsso** [comment]
Faut se sync avec Romain, il me semble qu'il a un peu regardé les rôles :)

**Comment by Florto** [comment]
Support_member serait-il utile ? Pour les recherches et suppressions de compte ?

**Comment by carsso** [comment]
@Florto T'as complètement raison, pour avoir l'état d'un compte et renvoyer les emails lost pw / confirmation
Il manque peut-être dans le même genre un supply_member (ou autre nom) pour accompagner les centres, cf #284 et l'accès a la recherche avec la carte avec les stats pour avoir une idée des volontaires/ages autour d'un centre

**Comment by ssaunier** [comment]
ℹ️ [`pundit`](https://github.com/varvet/pundit) est une gem qui permet la gestion **back-end** des autorisations. Ça ne fournit pas de UI. La gem actuelle [`rolify`](https://github.com/RolifyCommunity/rolify) de rôle (qu'on va guarder) ne fournit pas de UI non plus

Si on part sur autant de rôles, il va falloir une solution pour visualiser / éditer / auditer ces rôles (et pas faire du `scalingo run bin/rails c` à chaque fois). Est-ce que les gems de Admin UI (`rails_admin`, `active_admin`, `administrate`, `madmin`, etc.) sont adaptées, y a-t-il un plugin Rolify UI, ou devrions-nous construire notre solution ? Question ouverte

**Comment by rchampourlier** [comment]
Rien à rajouter de mon côté sur les rôles, ce qui est dans la suggestion me semble complet de ce que j'ai vu jusque là.

Mes quelques remarques à chaud :
- Je n'ai pas le sentiment qu'une gem d'Admin UI soit nécessaire pour gérer les rôles, je me dis que ce serait utile si on avait plein de vues de type admin à créer, si c'est pour les rôles ça pourrait être plus simple de faire à la main. Je n'ai rien trouvé d'évident qui soit intégré avec Rolify pour le moment.
- Ça peut valoir le coût en effet de mettre pundit à cette occasion pour limiter le risque d'erreurs sur les autorisations.

**Comment by mathieuripert** [comment]
> Rien à rajouter de mon côté sur les rôles, ce qui est dans la suggestion me semble complet de ce que j'ai vu jusque là.
> 
> Mes quelques remarques à chaud :
> 
> * Je n'ai pas le sentiment qu'une gem d'Admin UI soit nécessaire pour gérer les rôles, je me dis que ce serait utile si on avait plein de vues de type admin à créer, si c'est pour les rôles ça pourrait être plus simple de faire à la main. Je n'ai rien trouvé d'évident qui soit intégré avec Rolify pour le moment.
> * Ça peut valoir le coût en effet de mettre pundit à cette occasion pour limiter le risque d'erreurs sur les autorisations.

Je n'ai rien en tête non plus en terme d'UI pour la gestion des rôles. Mais ca ne me parait pas trop compliqué de le faire in-house. A décider quel rôle peut gérer les rôles (`admin` ?)

**Comment by carsso** [comment]
Il manque a ajouter support_member dans ta petite liste (support_admin aura plus de perms, comme delete un compte)

**Comment by rchampourlier** [comment]
@mathieuripert @carsso il reste encore des choses à faire là-dessus ? Je peux prendre le temps de regarder mais si vous avez la réponse à surface de 🧠 je prends ;)

**Comment by carsso** [comment]
Yep, y'a des petits trucs qui ont pas encore les bon ifs.
