### ISSUE TITLE
Add pundit policies 

### ISSUE THREAD

**Issue by adrienpoly** [hostolab/covidliste#311]
Following #309 we need to add dedicated pundit policies for each controller/resource

currently, in the controllers there is a function to bypass pundit

```ruby
def skip_pundit?
      # TODO add a real policy
      true
end
```

This function should be removed and proper authorization shall be performed on all the following controllers

- [ ] confirmation_controller
- [ ] matches_controller
- [x] partners
- [x] users
- [ ] admin/home
- [ ] admin/search
- [ ] admin/vaccincation_centers
- [ ] partners/campaigns
- [ ] partners/vaccincation_centers

Those are fairly simple contribution maybe a `good first issue` label can be added to and who ever wants to tackle one controller/policy can simply raise his hand in a comment to this issue.

**Comment by lukkor** [comment]
See #419 for the admin namespace.
