### ISSUE TITLE
Quand pourra t-on voir la liste des centres partenaires?

### ISSUE THREAD

**Issue by darrepac** [hostolab/covidliste#312]
Bonjour,

Je ne comprends pas pourquoi cette information n'est pas publique... quand c'est flou c'est qu'il y a loup ;)

**Comment by gwenvador** [comment]
Dans leur FAQ: "L’équipe de Covidliste diffusera bientôt la liste des professionnels de santé et lieux de vaccination inscrits. L’initiative a été lancée en partenariat avec des centres pilotes en Île-de-France et se développe sur l’ensemble du territoire." Je ne vois pas vraiment pourquoi on ne peut pas voir la liste aujourd'hui.
En Province ce serait bien de connaitre cette liste pour savoir si covidliste est utile..

**Comment by darrepac** [comment]
tout à fait...

**Comment by adrienpoly** [comment]
Je n'ai pas d'information à ce sujet, mais le projet étant open source peut être que vous pouvez proposer une PR pour ajouter cette fonctionnalité.

**Comment by Florto** [comment]
La question de la diffusion de la liste des lieux de vaccination inscrits est assez récurrente.

Nous comprenons que les utilisateurs de Covidliste souhaitent savoir s’il y a des lieux de vaccination disponibles dans leur région. C’est pourquoi nous avons réfléchi à une carte présentant le nombre de centres dans chaque région de France.

Il nous faut encore un peu de temps pour nous assurer de sa parfaite conformité avec la réglementation et nos standards de qualité, je propose de laisser l’issue ouverte en attendant.

**Comment by mininao** [comment]
Je me permet de fermer cette issue.
* La carte a été publiée
* Nous allons demander leur consentements aux centres qui souhaitent rendre publique leur inscription à Covidliste. Certains ne le souhaitent peut-être pas pour éviter que des personnes ne viennent alors qu'elles n'ont pas été matchées par covidliste
