### ISSUE TITLE
Page pour expliquer l'algorithme de matching

### ISSUE THREAD

**Issue by mathieuripert** [hostolab/covidliste#318]
Page qui explique comment fonctionne l'algorithme de matching. Egalement rajouter un lien depuis la FAQ

### Fonctionnement

https://github.com/hostolab/covidliste/blob/master/app/jobs/send_campaign_job.rb#L1

Le centre choisit:
- une distance en Km `D`
- une tranche d'age `[Age min, Age max]`
- un nombre de doses disponibles `N`

Les Volontaires "candidats" sont les volontaires qui:
- ont confirmé leur compte
- se situent à une distance `d < D`
- ont entre `Age min et Age max`
- n'ont pas été alertés au cours des X derniers jours

Ces candidats sont ensuite classés par ordre d'inscription.

Pour N doses disponibles, (N * Overbooking Factor) SMS sont envoyés aux premiers candidats.
Chaque volontaire averti a 6 minutes pour confirmer.

L'algorithme continue avec `N = N - volontaires confirmés` jusqu'à `N=0`

**Comment by lukkor** [comment]
Je m'assigne le sujet si tout le monde est OK ?

@mathieuripert je peux improviser un texte à partir de l'algo dans le code mais on sera sûrement plus efficace si tu as un texte à proposer.
