### ISSUE TITLE
"0 doses perdues" s'écrit au singulier

### ISSUE THREAD

**Issue by jdeniau** [hostolab/covidliste#322]
Bonjour,

La description sur github est "0 doses perdues" mais 0 est singulier, cela devrait donc être "0 dose perdue"

Je ne peux pas vous faire de PR pour la description github cela dit. 

![Screenshot_20210412_080909.jpg](https://user-images.githubusercontent.com/1398469/114348099-5e89f100-9b66-11eb-99a0-8f9d8671d1be.jpg)

**Comment by adrienpoly** [comment]
Je peux me renseigner avec des experts, mais je ne suis pas certains que cela soit réellement une faute.

En tout cas, c'est un sujet qui fait débat....

https://www.question-orthographe.fr/question/regle-du-zero/

**Comment by mathieuripert** [comment]
zero + zero = 2 x zeros = zero
Donc on pourrait très dire que zéro est pluriel :)

**Comment by jdeniau** [comment]
@adrienpoly effectivement, c'est toujours plus compliqué que ça visiblement 😉 

C'est au pluriel si on considère que c'est au pluriel si l'on réfléchit en terme de multiplication : (nombre de doses perdues) × 0
Mais au singulier si on compte et terme de "soustraction" : 3 doses perdues, 2 doses perdues, 1 dose perdue, 0 dose perdue

Je ferme cet "issue" du coup. Bravo pour l'initiative en tout ca 👍
