### ISSUE TITLE
Ajouter un espace presse

### ISSUE THREAD

**Issue by peiofour** [hostolab/covidliste#323]
L'idée c'est d'avoir un bouton "Espace presse" dans le footer, qui renvoie vers la liste de tous nos communiqués de presse.
Avec contact pour que les journalistes nous trouve facilement.

**Comment by mininao** [comment]
Un peu discuté [ici](https://covidliste.slack.com/archives/C01T48BHRCL/p1618057768060900) déjà pour info 😃
