### ISSUE TITLE
[Vaccin] Ajouter Johnson & Johnson (Janssen)

### ISSUE THREAD

**Issue by MatthieuGariel** [hostolab/covidliste#325]
Le vaccin Johnson & Johnson vient d'arriver dans la campagne de vaccination. Pour l'instant, nous n'en disposons pas dans l'interface de choix du vaccin. Il faut donc le rajouter.

**Comment by GuillaumeWrobel** [comment]
`Janssen` n'est-il pas le nom du vaccin de la firme `Johnson et Johnson` ? Auquel cas on l'a déjà dans `vaccine.rb`

**Comment by ssaunier** [comment]
Ah ouais donc en gros j'ai fait ça pour rien 🙈

**Comment by GuillaumeWrobel** [comment]
Si seulement il suffisait d'ajouter une ligne dans un fichier pour avoir un nouveau vaccin :smile: :syringe:

**Comment by colinemarie** [comment]
Marf oui je viens de voir la PR, j'allais dire qu'il existait déjà. On peut le renommer "Janssen Johnson et Johnson", comme ça c'est plus clair.

**Comment by ssaunier** [comment]
> Si seulement il suffisait d'ajouter une ligne dans un fichier pour avoir un nouveau vaccin 😄 💉
Oui clairement ce serait mieux, j'ai pas eu le courage de refacto le Data Model 🙈

**Comment by GuillaumeWrobel** [comment]
Par contre attention, dans les `Campaign`, voire ailleurs, le nom du vaccin est inscrit en dur dans la base de données, un renommage pourrait casser pas mal de choses.
