### ISSUE TITLE
Issue when displaying foreign phone numbers

### ISSUE THREAD

**Issue by rchampourlier** [hostolab/covidliste#326]
# The problem

- Users with foreign phone numbers (e.g. starting with +34 or +44) will not display correctly since it currently expect a match with number stored with a `33` prefix
- The number is correctly stored but wrongly displayed so it's confusing for users and they raise support issues

# What is expected

- We should only reformat the number to display `06 12 34 56 78` for French numbers
- Foreign numbers should be displayed as is, just prefixing them with `+`

**Comment by rchampourlier** [comment]
Please also check the current implementation works as expected depending on how the user enters the number. It's in `app/models/concerns/has_phone_number_concern.rb#format_phone_number`. In particular:
- check the format expected by Twilio,
- check for the different ways of entering a phone number: 033612345678, +3361234678, 0612345678...

**Comment by adrienpoly** [comment]
maybe we should implement this https://www.twilio.com/blog/international-phone-number-input-html-javascript

using this package https://github.com/jackocnr/intl-tel-input

**Comment by rthbound** [comment]
For server side: https://github.com/daddyz/phonelib
