### ISSUE TITLE
Ajouter une page /benevoles et un bouton vers le formulaire de recrutement

### ISSUE THREAD

**Issue by ElBulgaro** [hostolab/covidliste#328]
Un formulaire de recrutement a été créé pour permettre à l'équipe Covidliste de recruter des bénévoles.

Le formulaire a été créé sur la plateforme Typeform : https://form.typeform.com/to/UlzdGjLV

Il s'agit donc de créer une page (par exemple, covidliste.com/benevoles) contenant un texte pour expliquer la démarche de recrutement et un bouton (par exemple : "POSTULER") redirigeant vers le formulaire sur Typeform.

**Comment by marclrnt** [comment]
Voici une proposition de texte au-dessus du call-to-action :


-------------------------

Covidliste est une initiative bénévole et citoyenne qui a vu le jour Il y a quelques semaines pour accélérer la campagne nationale de vaccination contre le Covid19 en distribuant les doses sur le point d'être jetées.

Nous avons besoin de bénévoles pour venir renforcer nos rangs 💪

[BOUTON_CTA]

**Exemples de missions :**
- Contribuer au développement de la plateforme technologique
- Travailler sur les interfaces pour que le produit soit utilisable facilement par tout le monde
- Valider les nouveaux centres de vaccination partenaires
- Faire connaître le service covidliste auprès de nouveaux centres
- ...

**Voici des exemples d'engagements de certains de nos bénévoles :**
- 3h00 le mardi matin
- 1h00 le mercredi après-midi, jeudi après-midi et vendredi après-midi
- tout le lundi après-midi
- 3 heures le dimanche matin
- ....

[BOUTON_CTA]

-------------------------

Par ailleurs il faudra mettre à jour ceci :
![image](https://user-images.githubusercontent.com/8396084/114407055-505cc480-9ba8-11eb-8919-927cd4e6230e.png)
