### ISSUE TITLE
Ajouter un champ "informations spéciales" affiché avant confirmation dans les campagnes

### ISSUE THREAD

**Issue by carsso** [hostolab/covidliste#354]
Ce champ est défini par le centre de vaccination au moment de lancer une campagne.
On suggère dans ce champ (en fonction du type de vaccin) un message tout prêt mais on laisse au centre entièrement la main, c'est qu'un template.

Ce champ est affiché en évidence aux volontaires avant de confirmer le RDV. (genre dans un alert-primary)

Par exemple, pour AZ "Ce vaccin est contre indiqué pour les personnes avec des antécédents de ......".

Permettra d'éviter que des gens dont l'état de santé est incompatible, de valider un RDV et de se déplacer pour rien.

Dans un premier temps 1 vaccin = 1 template (il faut qu'on puisse en avoir 0)

On verra comment on les rédige une fois qu'on a la feature.

**Comment by mininao** [comment]
* Je sais pas si on veut vraiment cette feature ?
* Je pense qu'il doit y avoir un check de contre-indications fait par le centre de toute façon, et qu'il ne faut pas que le centre ait l'impression qu'il peut faire ce check via covidliste.
* Il y a probablement beaucoup de contre-indications possibles qu'on ne peut pas toutes lister

**Comment by navidemad** [comment]
Ya déjà un champ :extra_info dans le modèle Campaign, mais ouais je pense qu'ils savent pas trop quoi mettre comme informations dedans. Il est affiché une fois que le volontaire a confirmé son match sur la page qui suit l'envoi du formulaire.

**Comment by carsso** [comment]
C'est différent du extra info. Le extra info est affiché après la confirmation.
Là on parle d'un texte affiché avant.
