### ISSUE TITLE
Page d’admin - liste des domaines mail et statistiques pour les comptes non confirmées 

### ISSUE THREAD

**Issue by Florto** [hostolab/covidliste#355]
Pour permettre le contrôle du fait que nous ne sommes pas en train de subir d’attaque de bots, une page pour les admin_support serait utile, leur permettant d’accéder à la liste des domaines et le nombre de comptes non confirmés associés.

Ne pas afficher la liste des domaines où tous les comptes sont confirmés.

Pour faire le plus plaisir à @carsso vous pouvez le lui faire en petit graph camembert !

**Comment by Florto** [comment]
Pour ne pas tuer la base et pour le moment, on peut partir sur la visualisation paginée par heure !

**Comment by thbar** [comment]
Je vais jeter un oeil là dessus, au pire noter ce qui peut-être fait, au mieux faire une PR. @mathieuripert peux-tu me l'assigner ? Merci !

**Comment by mathieuripert** [comment]
Le seul souci, c'est que les emails sont chiffrés donc on ne pourra pas récupérer le domaine. Ou alors il faut créer une nouvelle colonne et stocker le domaine à part pour en faire des comptages

**Comment by thbar** [comment]
Le nom de domaine peut contenir des données personnelles également, donc il faudrait également le chiffrer.

Je pense qu'il faudra rediscuter du besoin de départ, pourquoi on cherche à faire ça etc, et voir si c'est la bonne stratégie pour satisfaire le besoin ou pas.

Mon planning est pour l'instant trop chargé, je vais devoir me dé-assigner pour l'instant.

**Comment by rchampourlier** [comment]
@Florto est-ce que la mesure du rythme de création de comptes et l'éventuelle observation d'une anomalie ne répondrait pas également au besoin ?

**Comment by carsso** [comment]
J'ai l'impression que le nouveau fournisseur email affiche les top domaines dans des stats.
