### ISSUE TITLE
Ajouter la date du RDV sur la page reçue par SMS d'un match qui a confirmé sa dispo

### ISSUE THREAD

**Issue by carsso** [hostolab/covidliste#364]
Au niveau du  Créneau horaire, le volontaire qui a confirmé devrait pouvoir avoir la date du RDV.
Certains utilisent ce document comme preuve de RDV avec leur attestation de déplacement.
Le fait que la date soit absente est un problème.

**Comment by colinemarie** [comment]
@carsso c'est bon avec #431 non ?

**Comment by carsso** [comment]
Yep
