### ISSUE TITLE
Ajouter la possibilité de refuser un RDV sur la page reçue par SMS par un match

### ISSUE THREAD

**Issue by carsso** [hostolab/covidliste#365]
Plusieurs remontées de personnes qui s'étonnent de ne pas avoir de bouton "pas disponible/refuser le RDV" sur la page reçue par SMS.
C'est vrai que ça pourrait être bien. Et potentiellement dans le futur on pourrait direct notifier le volontaire suivant, on gagnerai du temps.

**Comment by FelixMalfait** [comment]
Lorsqu'on refuse le rdv, idéalement il serait bien de pouvoir préciser si on refuse pour indisponibilité ou si l'utilisateur souhaite supprimer son compte, ça risque d'arriver de plus en plus souvent (cf mail au support d'un utilisateur qui demande à être supprimé car il a été vacciné entre temps mais reçoit encore des SMS)

**Comment by MatthieuGariel** [comment]
@FelixMalfait Agreed, on a de + en + de retour de gens déjà vaccinés qui nous le signalent lors de la réception d'un SMS/mail

**Comment by MatthieuGariel** [comment]
Je linke ça ici pour la désinscription d'un volontaire directement lors du match, qui s'inscrit dans une refonte globale des affichages / liens lors du match.

https://github.com/hostolab/covidliste/issues/424
