### ISSUE TITLE
[Security] Empêcher les bots de s'inscrire

### ISSUE THREAD

**Issue by mathieuripert** [hostolab/covidliste#370]
## Contexte / Problème
Des bots remplissent le formulaire d'inscription

## Proposition
Ajouter un captcha ?

cc @Florto @carsso

**Comment by Florto** [comment]
À mon avis, si pas trop d’effort : 
Captcha intégré (pas de service externe) + ajout de la méthode « champ caché »

**Comment by Florto** [comment]
Peut-on la passer P1 ? Car impact sur la réputation de notre domaine vis à vis des emails providers.

**Comment by carsso** [comment]
Si on trouve pas de captcha qui nous convient immédiatement, on peu rapidement écrire quelques questions de sécurité en rapport avec covidliste. Et on oblige a bien répondre. Ça va temporiser les bots quelques heures le temps de trouver une lib assez protectrice de la vie privée et qui bloque bien les robots en même temps.

**Comment by mininao** [comment]
Inspiration potentielle pour les questions : https://textcaptcha.com/

**Comment by FelixMalfait** [comment]
Une méthode moins efficace simple mais très simple, le 'honeypot captcha':
https://github.com/markets/invisible_captcha/
https://github.com/curtis/honeypot-captcha/

**Comment by mininao** [comment]
+1 @FelixMalfait , je pense que c'est ce que @Florto appelle "ajout de la méthode « champ caché »"

**Comment by Florto** [comment]
affirmatif :)

**Comment by peiofour** [comment]
Pourquoi ne pas utiliser le très pratique recaptcha de google ? https://www.google.com/recaptcha/about/

**Comment by mathieuripert** [comment]
> https://www.google.com/recaptcha/about/

Si on peut éviter de faire appelle à n'importe quel GAFA, c'est mieux! 
La méthode https://github.com/markets/invisible_captcha/ me parait un bon premier step

**Comment by mathieuripert** [comment]
@peiofour tu as du temps pour cette issue ?

**Comment by hack3rvaillant** [comment]
Est-ce que le recaptcha de google ne contiendrait pas un mouchard pour tracer les utilisateurs par hasard ?

**Comment by mathieuripert** [comment]
> Est-ce que le recaptcha de google ne contiendrait pas un mouchard pour tracer les utilisateurs par hasard ?

pas impossible :)

**Comment by peiofour** [comment]
@mathieuripert  Oui je peux prendre, on part sur invisible captcha ?

**Comment by Florto** [comment]
Je confirme, je ne suis pas pour du tout de faire appel à un service externe de captcha et encore moins non Français, il suffit de voir le tollé qu’avait généré cela pour stopcovid en son temps !

**Comment by hack3rvaillant** [comment]
Il me semble qu'on utilise Datadog et que sqreen a été racheté par eux.
Je me souviens que Sqreen avait une iA pour détecter les bots super efficace.
Est-ce que ça fait parti de l'offre Datadog ?
