### ISSUE TITLE
Ajouter une validation des informations personnelles au moment de la validation du RDV

### ISSUE THREAD

**Issue by carsso** [hostolab/covidliste#372]
Certains volontaires ont fait une erreur de saisie de leurs informations personnelles.
Au moment du RDV, l'information est clé pour le centre et des mauvaises infos empêchent la vaccination.

Dans la page qui permet de valider un RDV, reçue par SMS, il faut reprendre le formulaire permettant de modifier ses données comme dans l'espace membre.
Chaque champ doit pouvoir être modifiable.
En dessous de chaque champ, ajouter une case à cocher "Je confirme que <xxxx> est valide" (où xxxx est le nom du champ)
En bas du formulaire ajouter un champ "Je certifie sur l'honneur que les informations communiquées ci-dessus sont exactes."

Au moment de la validation, vérifier que les information renseignées correspondent aux contraintes de la campagne.
Si ce n'est pas le cas, alors il faut exclure le volontaire (en considérant qu'il a refusé le match ?).
Si #365 est déjà codée, ce sera facile, sinon, simplement mettre un if qui masque le formulaire et qui dit "Désolé, vous ne correspondez pas aux critères..." et on attends l'expiration des 10 minutes, c'est pas grave.

**Comment by FelixMalfait** [comment]
J'ai peur que ça complexifie la structure et le flow d'acceptation d'intégrer l'édition dedans, non ?
On peut peut-être commencer par une implémentation plus simple qui link vers la page d'édition pour éviter de la dupliquer ?

Par exemple se limiter à afficher une modale de confirmation  ?
**Titre**:  Je certifie l'exactitude des informations"
**Sous-texte**: Rendez-vous pour Prénom Nom,  né le Date de naissance
**Sous-texte**: Toute erreur sur la personne où l'âge aboutira à un refus et une exclusion de la plateforme."
**CTA-in**: Ces informations sont exactes
**CTA-out**: Modifier les informations

**Modale - option 1**
Afficher la modale dès l'ouverture de la page (avec éventuellement une opacité supérieure)
-> Permet de masquer l'adresse du centre avant confirmation pour curieux / tricheur

**Modale - option 2**
Afficher la modale de confirmation au clic sur 'Je suis disponible'
-> Moins agressif

**CTA-out - Option 1**
CTA renvoie sur un controller intermédiaire qui sort l'utilisateur de la campagne puis le redirige vers la page de modification. Flash message sur la page d'édition :
"Merci de corriger vos informations. Vous serez contacté si de nouvelles doses sont disponibles. "
-> Sanctionne les tricheurs/curieux mais peut décevoir des gens honnêtes qui voulaient faire une correction mineure

**CTA-out - Option 2**
CTA renvoie vers la page de modification sans controller intermédiaire, avec un flash message:
"Merci de corriger vos informations et de retourner au plus vite sur ce lien pour indiquer votre disponibilité"
-> Moins dissuasif pour des tricheurs mais évite d'exclure des âmes bien intentionnées

Enfin je te laisse arbitrer, la solution initiale fonctionne bien aussi :)

**Comment by carsso** [comment]
Pour aller vite, solution suggérée:

On affiche juste chaque champ prénom, nom, date de naissance
On met 1 case a cocher pour chaque pour confirmer que la valeur est bonne
+ 1 case en bas où on certifie pour l'honneur

on ajoute également un lien vers le profil utilisateur qui permet de modifier les infos

Avant d'afficher le formulaire ou avant de confirmer le RDV, on vérifie que l'age calculé a partir de la date de naissance est toujours dans la range de la campagne
Si il est hors range on met un message en disant qu'on est désolé et que la personne ne remplis pas les critères d'attribution de la dose.

**Comment by carsso** [comment]
P1 pour la version rapide.
Dans un 2eme temps on se posera pour un truc plus sympa, avec modal etc... cette partie là P2

**Comment by mininao** [comment]
En version extra extra rapide pour shipper ça en 30minutes, je vais juste faire des cases "je confirme que c'est bon" et laisser l'édition de côté.

**Comment by carsso** [comment]
Yes, la priori n°1 c'est ça, avec un bouton pour aller sur le profil et bloquer le form si la personne a changé la date dans son profil et que ça match plus :)

**Comment by MatthieuGariel** [comment]
Je linke ça ici pour la désinscription d'un volontaire directement lors du match, qui s'inscrit dans une refonte globale des affichages / liens lors du match.

https://github.com/hostolab/covidliste/issues/424

**Comment by carsso** [comment]
Ajouter également une case "En acceptant le RDV je m'engage à me rendre sur place à l'heure prévue pour ne pas perdre de dose"

**Comment by mininao** [comment]
Vu qu'on va demander le nom/prénom au moment du match maintenant, et qu'on demande bien confirmation que les infos sont valides, je me permet de fermer l'issue.
