### ISSUE TITLE
Sensibiliser les centres de vaccination pour éviter le surbooking

### ISSUE THREAD

**Issue by FelixMalfait** [hostolab/covidliste#377]
## Contexte / Problème
Des centres ont lancé une campagne mais les patients qui se sont rendu sur place n’ont pas pu être vacciné car les doses avaient déjà été distribuées.

## Proposition
1 — ajouter une explication côté partenaire pour les sensibiliser
Modifier la modale de confirmation.
“Un SMS sera immédiatement envoyé aux volontaires pour confirmer leur disponibilité. Vous avez indiqué que {x} doses pourraient être injectées à l'horaire indiqué, merci de confirmer cette capacité et de ne pas indiquer un nombre supérieur à celui effectivement disponible.“

2 — ajouter un disclaimer côté volontaire pour indiquer le rôle de plateforme de CovidListe
“Covidliste est une plateforme de mise en relation, par conséquent nous ne pouvons garantir à 100% la fiabilité des informations fournies. En cas de doute, contactez le centre de vaccination."

**Comment by hack3rvaillant** [comment]
Arf #239 n'a pas suffit ou bien c'est juste que c'est des campagnes qui avaient déjà été lancées ?

**Comment by FelixMalfait** [comment]
Merci @hack3rvaillant, de ce que je vois #239 c'était un surbooking lié au comportement du système. Ici le problème c'est que l'équipe reçoit des plaintes de volontaires convoqués qui se sont rendus sur place mais n'ont pas pu avoir accès à une dose. L'idée c'est juste d'un côté sensibiliser les centres de vaccination et de l'autre rappeler que Covidliste n'est qu'une plateforme de mise en relation.

**Comment by lukkor** [comment]
J'attends le merge de #368 pour avancer sur le sujet.
