### ISSUE TITLE
Migrer de Turbolinks vers Turbo

### ISSUE THREAD

**Issue by navidemad** [hostolab/covidliste#381]
## Contexte / Problème

Turbolinks n'est plus maintenue à jour par DHH.

> Please note that Turbolinks is no longer under active development. It has been superseeded by a new framework called [Turbo](https://github.com/hotwired/turbo), which is part of the [Hotwire](https://hotwire.dev) umbrella.

## Proposition

Le développement de Turbolinks n'étant plus actif, il a été repris et boosté par un nouveau framework appellé [Turbo](https://github.com/hotwired/turbo).
Je propose de migrer vers Turbo dans un premier temps, puis vers Hotwire dans un second, en sachant que Rails 7 arrive bientôt et qu'il sera par défaut configuré avec.

**Comment by adrienpoly** [comment]
Turbo drive et presque identique à Turbolinks et la migration peut être très simple. Par contre, Turbo Drive et packagé avec TurboFrames qui lui apporte pas mal de breaking change notamment sur la gestion des forms.

Une solution est d'utiliser Drive dans un premier temps et d'opt out de Frame. 
Cf last comment ici https://github.com/hotwired/turbo/pull/95

**Comment by navidemad** [comment]
Ouais je pensais d'abord dans un temps 1 à faire utiliser turbo drive pour rendre asyncrone certains block qui peuvent mettre du temps, et temporaire le désactiver pour les form et les liens en data-method

**Comment by EmCousin** [comment]
Il faut également faire en sorte que le serveur retourne un code >= 400 dans sa réponse dans certains cas. Le cas le plus emblématique est lorsqu'une resource n'est pas valide lors d'une création ou d'une mise à jour.
Par défault, le Rails scaffold rend le template de création ou d'edit de la resource avec un code 200. Il faut simplement ajouter un `status: :unprocessable_entity`. De mémoire, le générateur de scaffold le fera tout seul dans Rails 7.

**Comment by navidemad** [comment]
En effet, le rendering lors des erreurs faire juste un render classique retournera un code 2xx qui fera que certaines choses dans la frame ne seront pas notifié, après avec le gamestyle de certain rendering dans le code, faut que j'adapte un petit peu.
