### ISSUE TITLE
Faire une page FAQ pour les pros

### ISSUE THREAD

**Issue by carsso** [hostolab/covidliste#386]
Les pros aussi ont des questions, il faut leur faire une FAQ dédiée.
La lier a la première en partie (potentiellement avec un type sur FaqItem) ?.

Voir avec la team sur Slack pour les questions, ils vont essayer de les regrouper.

**Comment by rchampourlier** [comment]
Sauf erreur, ça a été fait, donc je ferme l'issue : https://www.covidliste.com/partenaires/faq

**Comment by carsso** [comment]
Yep, dans #601
