### ISSUE TITLE
Volontaires "matchés" plusieurs fois en 24h

### ISSUE THREAD

**Issue by mathieuripert** [hostolab/covidliste#394]
## Contexte / Problème

Il arrive que deux SMS soient envoyés à la même personne en même temps. C'est lié au fait que le service qui fait les matchs est asynchrone, d'où l'existence de "race conditions"

## Proposition

Vérifier au moment de la création du match que le user n'a pas été matché dans les dernières 24h.
Eventuellement, faire le check + création du match dans une seule et même transaction DB. Je ne crois pas qu'on soit obligé de faire un redis lock.

## Priorité (Requis)

Ajouter un label `Priorité`

- `P2`: Moyennement urgent, à résoudre en 4 jours

**Comment by mininao** [comment]
Normalement réglé
