### ISSUE TITLE
[Documentation] Vue générale de la plateforme

### ISSUE THREAD

**Issue by mathieuripert** [hostolab/covidliste#397]
## Contexte / Problème

Aider les nouveaux contributeurs.

## Proposition

Ajouter dans `handbook.md` une vision générale de ce que fait la plateforme et les différents modèles.

- Interface Admin
- Interface Volontaires
- Interface Partenaires
- Definition des différents modèle (`VaccinationCenter`, `Campaign` , etc...)

## Priorité (Requis)

- `P2`: Moyennement urgent, à résoudre en 4 jours

**Comment by omontigny** [comment]
Hello, peut-être l’avez-vous déjà mais un schéma de la BDD ça vous intéresse ?

**Comment by thegrif** [comment]
J'ai de l'expérience dans la gestion d'un système similaire à covidliste à New York. 

Je ne parle pas français. Si nous pouvons utiliser Google Translate, je serai heureux de vous aider à rédiger les documents techniques de la plate-forme.
