### ISSUE TITLE
Modifier âge maximum sur formulaire d'inscription

### ISSUE THREAD

**Issue by MatthieuGariel** [hostolab/covidliste#399]
## Contexte / Problème

Plusieurs utilisateurs ont remonté ne pas pouvoir sélectionner un âge supérieur à 90 ans sur notre interface. En effet, nous  bloquons la date de naissance en 1931. // De plus on autorise nos partenaires à sélectionner une fourchette d'âge supérieure à 90 ans, donc pas cohérent avec l'input user.

## Proposition

Modifier le [form d'inscription](https://github.com/hostolab/covidliste/blob/d7e040b1b676b4c995e8453dac24ceef26b5153b/app/views/users/_form.html.erb) afin d'autoriser les gens à entrer une date de naissance jusqu'à 120 ans (valeur arbitraire maximale).

## Priorité
P3: Pas prioritaire

**Comment by mathieuripert** [comment]
done !
