### ISSUE TITLE
Revoir le wording et les explications de la fonction annuler

### ISSUE THREAD

**Issue by mininao** [hostolab/covidliste#401]
## Contexte / Problème

* Le fonctionnement de la fonctionnalité "Annuler" n'est pas clair.
* Aujourd'hui elle interrompt l'envoi de nouveaux matchs. Les matchs envoyés sont toujours confirmables, et ceux confirmés le restent.

## Proposition

* Renommer la feature en "Arreter"
* Clarifier ce qu'il se passe avec les volontaires ayant confirmé
* Clarifier qu'il faut les contacter si on veut les annuler
* A decider si on veut également empêcher les volontaires de confirmer. Cela peut générer une déception.

**Comment by carsso** [comment]
En rapport avec #356 je suggère"Interrompue manuellement"

Quelques idées que je reprends depuis l'autre issue :
Il faudrait également que pendant les 15 minutes (délai d'une vague d'envoie + 5 minutes) qui suivent une annulation ce soit "En cours d'interruption".

Quand une campagne est "En cours d'interruption" afficher un warning sur la page de la campagne disant que la liste des volontaires n'est pas encore complète.

**Comment by mininao** [comment]
Implémenté
