### ISSUE TITLE
A-t'on besoin de pages dynamiques ?

### ISSUE THREAD

**Issue by EmCousin** [hostolab/covidliste#404]
## Contexte / Problème

Il y a régulièrement des issues qui sont ouvertes concernant l'ajout / la modification de pages.
Exemples : https://github.com/hostolab/covidliste/issues/328, ou encore ici : https://www.covidliste.com/presse

## Proposition

Les pages les plus simples affichant des informations diverses pourraient bénéficier d'un léger CMS, ce qui permettrait à des volontaires en communication de travailler sur le projet sans passer par la case programmation.

Solution technique proposée : j'ai une PR prête, que je n'ai pas encore ouverte, qui propose une solution pour les superadmins avec ActionText.

## Limites

Les pages les plus sensibles comme Mentions Légales, Confidentialité ou encore Algorithme ne seraient pas concernées et resteraient statiques et versionnées sur Github pour des raisons de transparence. Les pages les plus complexes comme la FAQ ou les cartes comprenant des données dynamiques non plus.

## Priorité (Requis)

Probablement P3, peut-être P2

- `P2`: Moyennement urgent, à résoudre en 4 jours
- `P3`: Pas prioritaire

**Comment by rchampourlier** [comment]
@navidemad j'ai l'impression que tu as pris le lead sur une feature de mini-CMS. Selon le statut, je te laisse voir s'il on peut fermer cette issue ?
