### ISSUE TITLE
Empêcher la création de campagne postérieure à la date de RDV

### ISSUE THREAD

**Issue by MatthieuGariel** [hostolab/covidliste#405]
## Contexte / Problème

Nous avons observé ce matin des [modalités anormales](https://covidliste.slack.com/archives/C01T48BHRCL/p1618448211440400) de lancement de campagnes. En effet, certains partenaires lancent des campagnes pour des horaires antérieurs à la campagne. Or, l'utilisateur reçoit un message qui indique que le RDV est le jour-même et postérieur au SMS.

## Proposition

@mininao [a proposé](https://covidliste.slack.com/archives/C01T48BHRCL/p1618470825462500?thread_ts=1618448211.440400&cid=C01T48BHRCL) le fonctionnement suivant : Bloquer les créneaux horaires (start > create, stop > create + 40mn, stopper la campagne 15mn avant la fin)

Les 40/15 minutes peuvent être discutées mais il faut que cela soit bloquant pour le partenaire, et qu'il choisisse un créneau de RDV postérieur au début de sa campagne.

## Priorité (Requis)

P2

**Comment by FelixMalfait** [comment]
Top ! + changer les valeurs par défaut à la création de campagne (pour now + 10min ; now + 70min par ex). Sinon comme ajd la borne min par défaut est l'heure au chargement de la page et que l'utilisateur peut mettre plus d'une minute à créer la campagne, ça créerait un peu de friction.

**Comment by carsso** [comment]
Demandé par la team : Mettre un buffer d’**une heure** entre le lancement d’une campagne et la campagne elle-même

**Comment by MatthieuGariel** [comment]
Attention : une heure ça peut-être vraiment trop important. Certains lancent la campagne en fin de journée, et vraiment pour des doses qu'il reste.

Pour moi, il vaut mieux juste déjà forcer à avoir un horaire post-début de campagne, éventuellement un buffet mais 1h ce sera trop. Éventuellement un warning pour leur dire "attention la campagne et l'horaire de RDV se chevauchent"

**Comment by mininao** [comment]
Done
