### ISSUE TITLE
Share to Twitter after account is activated / Partager sur Twitter une fois son compte activé

### ISSUE THREAD

**Issue by ElBulgaro** [hostolab/covidliste#41]
Voici un exemple d'URL pour un partage vers Twitter : https://twitter.com/share?url=Je%20viens%20de%20m'inscrire%20sur%20%40covidliste%20pour%20recevoir%20une%20alerte%20d%C3%A8s%20qu'une%20dose%20de%20vaccin%20sera%20disponible%20pr%C3%A8s%20de%20chez%20moi%20!%20%F0%9F%92%89%0A%0APour%20s'inscrire%20%3A%20https%3A%2F%2Fwww.covidliste.com%2F%0A%0A%23AucuneDosePerdue

Voici ce que ça donne : 

![image](https://user-images.githubusercontent.com/34547278/113453970-6c71a080-9407-11eb-9346-9f6571e4991d.png)

Et voici le code de base pour ajouter un lien sur le site : 

`<a href='https://twitter.com/share?url=Je%20viens%20de%20m'inscrire%20sur%20%40covidliste%20pour%20recevoir%20une%20alerte%20d%C3%A8s%20qu'une%20dose%20de%20vaccin%20sera%20disponible%20pr%C3%A8s%20de%20chez%20moi%20!%20%F0%9F%92%89%0A%0APour%20s'inscrire%20%3A%20https%3A%2F%2Fwww.covidliste.com%2F%0A%0A%23AucuneDosePerdue'></a>`

**Comment by DavidLibeau** [comment]
Bonjour,
Proposer aux usagers de partager sur les réseaux sociaux "Je viens de m'inscrire sur @covidliste" partage également l'information sur la non vaccination de la personne. Face à l'inculture de bon nombre de personne sur les données personnelles et la possibilité d'utiliser les tweets pour du ciblage publicitaire (par exemple), il est proposé de changer le message du tweet par un texte plus neutre et de permettre de réaliser ce tweet dès la page d'accueil. Cela permettra également à plus de personne de le partager si jamais celles-ci veulent le faire après coup.
