### ISSUE TITLE
Ajouter un bouton "Se désinscrire" lors du SMS/mail de match OU dans le match

### ISSUE THREAD

**Issue by MatthieuGariel** [hostolab/covidliste#424]
## Contexte / Problème

Le nombre de matches croit chaque jour. Nous recevons un nombre croissant de retours d'utilisateurs souhaitant se désinscrire lors de la réception du SMS / mail de match. Nous allons en recevoir de plus en plus si le nombre de matches croit sur la même dynamique.

## Proposition

- Intégrer dans le mail/SMS une URL "Vous pouvez vous désinscrire en cliquant ici"
- OU ajouter un bouton de désinscription dans le match AVEC indication de la possibilité de se désinscrire dans le texte du SMS/mail (sinon on va recevoir quand même des retours)

Cela permettra également d'apurer et alléger notre base de données.

## Priorité (Requis)
P2

**Comment by adrienpoly** [comment]
C'est encore d'actualité ? Ou #470 adresse entièrement cette issue ?

Avec le sign in Password Less cela rajoute probablement un A/R supplémentaire entre le site et le client mail.

Peut-être que lors du clic de ce lien on pourrait générer automatiquement un mail de login

**Comment by MatthieuGariel** [comment]
@adrienpoly Nope [#470](https://github.com/hostolab/covidliste/pull/470) rajoutait uniquement un lien vers le login dans le match.

Tu veux dire qu'on aurait un lien, dans le mail de match, qui générerait un autre mail de login ?
Perso ça m'irait très bien !

À voir quand l'implémenter également dans le match (comme la refonte est en cours).

**Comment by mathieuripert** [comment]
Et pourquoi pas directement un lien dans l'email de match qui supprime le compte ?
