### ISSUE TITLE
Rendre la carte des centres de vaccination accessible

### ISSUE THREAD

**Issue by DavidLibeau** [hostolab/covidliste#425]
## Contexte / Problème

La carte des centres de vaccination n'est pas accessible. Les personnes utilisant un lecteur d'écran n'ont accès à aucune information.

## Proposition

Suivre les règles d'accessibilité du W3C ou [les règles définies par Fizz.studio pour les visualisation de données](https://chartability.fizz.studio/).

Mettre en ligne les données sous forme de liste HTML.

## Priorité (Requis)

La priorité doit être décidée par les personnes en charge de la gestion du projet.

**Comment by Florto** [comment]
+1

David vous semblez bien maîtriser le sujet de l’accessibilité. Étant donné que ce sont des compétences spécifiques, nous acceptons volontiers une PR sur ce sujet. Et n’hésitez pas à nous remonter voire corriger les autres soucis d’accessibilité.

Si vous n’avez pas le temps, la possibilité ou l’envie de la développer, on l’ajoute à notre backlog. Par contre, ça ne sera pas P1 car nous avons encore des fonctionnalités qui pénalisent fortement l’usage actuel du projet.

Je suis tout à fait d’accord que notre objectif devrait être que les personnes utilisant un lecteur d’écran devraient avoir le même niveau de fonctionnalités que les autres. En attendant, en mode dégradé et bien que ça ne soit pas très satisfaisant, le service leur reste ouvert et la liste des centres de vaccination (utilisant ou non covidliste) est disponible sur les sites officiels.

**Comment by Florto** [comment]
Idéalement P2, mais je ne sais pas si objectivement on pourra respecter les 4 jours, donc peut-être plutôt P3.

**Comment by DavidLibeau** [comment]
Une simple liste HTML des centres suffit, à moins que vous souhaitez utiliser une carte en SVG mais qui reviendrais à jeter ce que vous avez déjà fait.

#273 demandait déjà la publication de la liste des centres de vaccination mais cette issue a été fermée. Il faut clarifier quelles informations vous souhaitez publier avant de proposer une implémentation technique. A l'heure actuelle, seules les coordonnées GPS sont publiques.

**Comment by Florto** [comment]
Pour le moment, je pense que rester sur un niveau de précision comparable à la carte serait intéressant.

Donc de façon simple je suggérerais nombre de centres par ville / code postal. Qu’en dites-vous ?

Pour la liste nominative des centres je pense qu’on n’est pas encore mûrs.
