### ISSUE TITLE
Ajout des CGUs côtés inscription partenaire

### ISSUE THREAD

**Issue by FelixMalfait** [hostolab/covidliste#427]
## Contexte / Problème
Absence de CGU pour les centre partenaires. Un projet sera envoyé ce soir (issue à mettre à jour)

## Proposition
1. Ajouter une nouvelle page qui contiennent les CGU
2. Ajouter un champs type tos_accepted_at dans les partenaires (utile d'avoir la date pour tenir compte des révision)
3. Ajouter une case à cocher en bas de formulaire d'inscription partenaire, du type 'En cochant cette case, vous certifiez avoir lu et accepté sans réserve les présentes'
4. Mettre à jour tos_accepted_at avec la date du jour lors de l'inscription

A suivre : comment faire signer les partenaires existants ? Mailing ? Ou middleware + page interstitielle à implémenter pour forcer la signature dans l'espace partenaire ?

**Comment by Florto** [comment]
Géré par #474
