### ISSUE TITLE
Autoriser les centres à lancer des campagnes dans les 7 prochains jours

### ISSUE THREAD

**Issue by laetitiajumel** [hostolab/covidliste#428]
## Contexte / Problème

Beaucoup de centres souhaitent pouvoir lancer des campagnes de vaccination au delà de la limite des 24h. Cela leur permettra d'étendre l'usage de Covidliste, qui ne sera plus seulement de ne pas perdre les dernières doses d'un flacon, mais aussi de planifier quand les flacons de vaccins pourront être ouverts, et s'assurer en avance d'avoir un nombre suffisant de personnes à vacciner. Cela permet de faciliter la tâche des vaccinateurs, qui peuvent être réticent à commander ou ouvrir certains flacons s'ils ne sont pas sûr de les finir, et ainsi d'accélérer la campagne de vaccination.

Ceci nous a été demandé plusieurs fois par les centres. Par ailleurs, les centres qui utilisent covidliste régulièrement mettent à disposition 6 doses par jour en moyenne - on est donc au dessus des niveaux attendus pour sauver les quelques dernières doses d'un flacon. Ceci signifie que les centres utilisent déjà Covidliste, malgré la contrainte des 24h, comme une liste d'attente pour utiliser leurs flacons non ouverts.

## Proposition

* Laisser aux centres la possibilité de lancer un appel à volontaires pour venir se faire vacciner dans les 7 jours qui suivent. 
* Idéalement, les volontaires se verront proposer un ou plusieurs créneaux (eg. lundi 9-12h, mardi 9-12h), et après confirmation, seront inviter à entrer en contact avec le centre pour prendre RDV (ce qui plusieurs centres font déjà).

## Priorité (Requis)

Ajouter un label `Priorité`

- `P2`: Moyennement urgent, à résoudre en 4 jours

**Comment by MatthieuGariel** [comment]
Je mets cette issue aussi ici car plusieurs partenaires qui rencontraient ce problème était dans ce cas et indiquaient des RDVs bien ultérieurs au créneau horaire défini + au créneau horaire où la campagne a eu lieu https://github.com/hostolab/covidliste/issues/405

**Comment by MatthieuGariel** [comment]
Attention, monter la durée de 6 minutes de confirmation à 20 va fortement ralentir l'envoi des campagnes pour les partenaires inscrits qui ont des doses "de fin de journée" à écouler. En l'occurence, en fonction des vaccins (et du taux de confirmation), ça peut être extrêmement pénalisant pour ces cas-là (qui restent très nombreux).

**Comment by FelixMalfait** [comment]
@MatthieuGariel désolé ce n'était pas clair. Je voulais dire monter la durée uniquement pour les campagnes qui ne sont pas des campagnes jour J.
