### ISSUE TITLE
Faire un group gem :production

### ISSUE THREAD

**Issue by navidemad** [hostolab/covidliste#433]
## Contexte / Problème

Certaines gem comme standard ne devrait-être que en group :development, tout comme :ddtrace qui devrait être qu'en :production non ?

## Priorité (Requis)

- `P3`: Pas prioritaire

**Comment by adrienpoly** [comment]
j'ai fait une tentative https://github.com/hostolab/covidliste/pull/367 mais on a finalement rollback. A la suite de cette PR il n'était plus possible de déployé en prod ? Juste pour info si quelqu'un se lance dans cette issue il faudrait faire un deploy de test sur un heroku ou autre pour s'assurer que cela deploy bien
