### ISSUE TITLE
Renforcer la politique de gestion des mots de passe

### ISSUE THREAD

**Issue by wajdiBen** [hostolab/covidliste#434]
## Contexte / Problème

Un utilisateur peut choisir un mot de passe faible composé juste de chiffre ( exemple 12345678 ) ou juste des lettres minuscules. Ce qui rend le site une cible parfaite pour différents type d'attaques de type Brute Force Attack ou bien Broken Authentication.

## Proposition

Renforcer la politique de gestion des mots de passe en suivant les bonnes pratiques : taille entre 8 et 64 caractères avec au moins 1 chiffre , au moins 1 caractère spécial , au moins 1 lettre minuscule et au moins 1 lettre majuscule.
A lire  https://owasp.org/www-project-top-ten/2017/A2_2017-Broken_Authentication.html 

Une fois que vous mettiez ça en place pour tout nouvel utilisateur, il faut implémenter un process pour obliger les utilisateurs déjà inscrit à mettre à jours leurs mot de passe. Par exemple , un utilisateur se connecte sur son compte et covidlist le forward à un formulaire de mis à jours de mot de passe.

## Priorité (Requis)

Ajouter un label `Priorité`

 `P1`: Urgent, à résoudre dans la journée

**Comment by Florto** [comment]
Je confirme. 

- 8 caractères minimums (je ne suis pas convaincu qu’un max soit nécessaire).
- 3 sortes de caractères parmi ces catégories : majuscules, minuscules, chiffres, caractères spéciaux

**Comment by rchampourlier** [comment]
@mathieuripert est-ce que je peux faire qqc pour t'aider sur celle-ci ?
