### ISSUE TITLE
[Confidentialité] - Empêcher Google et consorts de pister les utilisateurs via FloC

### ISSUE THREAD

**Issue by EmCousin** [hostolab/covidliste#436]
## Contexte / Problème

Google a activé par défaut une nouvelle méthode de pistage pour tous les utilsateurs de Google Chrome appelée Federated Learning of Cohorts (FLoC). Elle permet notamment de contourner des lignes de défense connues comme le blockage des cookies ou encore les AdBlockers.

Plus d'informations (en anglais) ici: https://spreadprivacy.com/block-floc-with-duckduckgo
Pour qui veut creuser davantage : https://github.com/WICG/floc

## Proposition

Bloquer le pistage FloC directement depuis le serveur. La solution est aussi simple que d'ajouter ceci dans l'entête de tous les réponses HTTP : `Permissions-Policy: interest-cohort=()`

## Priorité (Requis)

Je n'ai pas les droits pour mettre des labels sur les issues, mais je considère que c'est du **P1**

**Comment by mininao** [comment]
Hello 👋 
A priori c'est déjà fait grâce à @gearnode : https://github.com/hostolab/covidliste/pull/423
