### ISSUE TITLE
Afficher les infos et les chiffres dans le formulaire d’édition

### ISSUE THREAD

**Issue by Florto** [hostolab/covidliste#438]
## Contexte / Problème

Une fois connecté, impossible d’avoir les détails sur ce qu’est covidliste et les chiffres sur le nombre d’inscrits, de contactés, de centres,…

## Proposition

Reprendre les infos à droite du formulaire d’inscription et les mettre à l’identique à droite du formulaire d’édition.

## Priorité (Requis)
P3

**Comment by mininao** [comment]
Je me permets de fermer l'issue pour la fusionner avec https://github.com/hostolab/covidliste/issues/543
