### ISSUE TITLE
Prevent users from being matched twice in a day because of a race condition

### ISSUE THREAD

**Issue by mininao** [hostolab/covidliste#440]
## Contexte / Problème

* On sélectionne les users matchés assez longtemps avant de créer le match et d'envoyer le mail/SMS
* Parfois des users sont sélectionnés par deux campagnes différentes en même temps (race condition)
* Cela représente ~1000 notifications / jour (soit 45 euros de SMS)

## Proposition

* Juste avant de créer le match ou d'envoyer les notifications, vérifier que l'utilisateur n'a pas été matché aujourd'hui

**Comment by bastarte** [comment]
Idem que #394
