### ISSUE TITLE
Afficher une map statique avant confirmation du match

### ISSUE THREAD

**Issue by MatthieuGariel** [hostolab/covidliste#446]
## Contexte / Problème

Lors d'une [campagne importante](https://covidliste.slack.com/archives/C01TKMUTP4M/p1618583494105800) (~50 doses), un partenaire inscrit nous a remonté que plusieurs personnes n'ayant pas confirmé le match se sont présentées. En effet, nous affichons l'adresse du centre pour permettre aux gens de savoir s'ils peuvent se rendre sur place. Sauf que certains ne valident pas le match se présentent car l'adresse reste assez précise.

## Proposition

Afficher une map statique qui permet d'approximer la position du partenaire de visu
(ou toute autre solution qui permet à l'user de savoir à peu près où est le lieu // s'il peut s'y rendre // sans connaître l'adresse précisé)

## Priorité (Requis)
P2

**Comment by MatthieuGariel** [comment]
Réflexion autour du fait de pouvoir, pour le partenaire, identifier les matchs confirmés plutôt que de cacher des informations qui pourraient être utiles au volontaire pour savoir s'il peut se rendre ou non au lieu de vaccination.

**Comment by Florto** [comment]
Un code unique communiqué au patient matché confirmé  et dispo pour le centre serait une bonne solution !

**Comment by navidemad** [comment]
Code unique par patient ou code unique par centre ?

**Comment by MatthieuGariel** [comment]
Je penche plutôt pour une identification, un code, une couleur, pour l'ensemble de la campagne.

Ça simplifie le travail et la compréhension pour tous, en poursuivant bien l'objectif d'identification.

**Comment by mininao** [comment]
[Discussion sur slack](https://covidliste.slack.com/archives/C01T5RYDRAS/p1618602412096200?thread_ts=1618594268.083900&cid=C01T5RYDRAS)

**Comment by mininao** [comment]
Je ferme l'issue pour l'instant, vu qu'on va probablement pas partir sur la solution "map statique"
