### ISSUE TITLE
Filtrer par simple ou double dose

### ISSUE THREAD

**Issue by jucdn** [hostolab/covidliste#448]
## Contexte / Problème

Certains centre de vaccination souhaitent pouvoir filtrer leur campagne par "simple ou double dose" (une seule dose est nécessaire pour les personnes ayant contracté la Covid il y a plus de trois mois).
En effet la gestion de la deuxième ne pourrait être garantie par le centre de vaccination si le volontaire à la vaccination en fait pas encore partie des personnes éligibles à la vaccination.

## Proposition

- Permettre à l'inscription en tant que candidat de sélectionner si il ne doit bénéficier que d'une seule dose
- Permettre aux centres de vaccination de filtrer les campagnes pour les personnes nécessitant uniquement une seule injection.

## Priorité

P2

## Attention

Je ne pense pas que l'application soit déployée chez un hébergeur de données de santé, et donc je ne suis pas sûr qu'il soit possible de poser la question : "Avez-vous contracté la Covid il y a plus de 3 mois ?"

**Comment by FelixMalfait** [comment]
C'est vrai que c'est un vrai problème ceux qui veulent donner une seule dose.
En revanche je ne suis pas convaincu par la solution, au delà du problème de collecter une donnée supplémentaire que tu mentionnes, je pense que peu de gens sont dans le scénario où ils ne doivent bénéficier que d'une dose, et que pour ces gens là la donnée deviendrait vite fausse car ils pourraient entre-temps obtenir leur seconde dose ailleurs. 
Comme il n'y a pas eu de réponse, je proposer de fermer bientôt l'issue mais on peut la réouvrir si quelqu'un a d'autres idées d'implémentation, car c'est un bon point !
