### ISSUE TITLE
Suivi des recommandations par un confrère lors des inscriptions des centres

### ISSUE THREAD

**Issue by carsso** [hostolab/covidliste#450]
## Contexte / Problème
Suite de #285 
Faire en sorte que le lien qu'on suggère d'envoyer par mail permette de savoir qui a recommandé qui.
Pourvoir remercier les centres / personnes qui sont des évangélisateurs de l'outil :muscle:.

**Comment by rchampourlier** [comment]
@carsso est-ce qu'on garde cette issue ?

**Comment by carsso** [comment]
Je crois que la team partenaires en voulait donc je dirais oui
