### ISSUE TITLE
Indiquer aux centres qu'ils seront bientôt contactés pour être validés si ils sont en attente

### ISSUE THREAD

**Issue by carsso** [hostolab/covidliste#451]
Ajouter message une fois l’inscription d'un centre réalisée précisant que
- ils vont etre contactés par covidliste
- que si c’est une erreur ils peuvent supprimer leur centre
- implémenter la suppression de centres non validés

Voir #359 pour inspiration

**Comment by mininao** [comment]
En prod je crois
