### ISSUE TITLE
Ajouter des opt-in pour les centres de vaccination pour choisir si ils veulent diffuser leur nom et localisation et acceptent qu'on communique sur eux sur RS+médias

### ISSUE THREAD

**Issue by carsso** [hostolab/covidliste#473]
## Contexte / Problème

Certains professionnels de santé ne veulent pas diffuser le nom ni la localisation précise de leur établissement sur la carte.
Il faut aussi qu'on leur demande si ils acceptent qu'on les cite en terme de communication (twitter, médias, etc..).

## Proposition

Proposer un premier opt-in (case à cocher) champ leur permettant de choisir d'apparaitre de manière précise et sous le nom sur la carte Covidliste.  Sinon ils apparaitront sous forme d'un "Lieu de vaccination" avec des coordonnées GPS aproximées (partiellement aléatoires)
Proposer un second opt-in (case à cocher) champ leur permettant de choisir si ils acceptent que nous fassions de la communication externe sur leur inscription (twitter, médias, etc...)
Il faut qu'ils puissent changer ça a tout moment dans l'espace partenaires.

Mettre à jour le code de la carte pour faire l'approximation des centres qui n'ont pas accepté et masquer leurs noms en indiquant "Lieu de vaccination" (pour l'instant ce dernier code est commenté)
Potentiellement faire des méthodes public_name, public_lat, public_lon dans l'objet vaccination_center qui sont dépendantes de l'opt-in concerné.

Pour le naming du 1er opt-in en db : public_display, public_details, ... _autres idées ?_
Pour le naming du 2ème opt-in en db : public_communication, ... _autres idées ?

**Comment by mathieuripert** [comment]
Ma suggestion, mais textes à challenger et à améliorer

## Opt-in 1 
Texte:
```
En cochant cette case, vous acceptez que les coordonnées du centre (nom, adresse) soient visibles sur le site Covidliste.
``` 
Nouvelle colonne dans `vaccination_center`: `visible_optin_at` (datetime)
Case à cocher au moment de la création du centre + espace partenaires.

## Opt-in 2
```
En cochant cette case, vous acceptez que Covidliste diffuse sur les réseaux sociaux et autres médias, des informations concernant l'inscription de ce centre.
``` 
Nouvelle colonne dans `vaccination_center`: `media_optin_at` (datetime)
Case à cocher au moment de la création du centre + espace partenaires.

**Comment by colinemarie** [comment]
@carsso @peiofour on en est où là-dessus ?

**Comment by carsso** [comment]
Oui oui oui oui.

**Comment by colinemarie** [comment]
Voir ce qui a été fait et peut être repris en #263 pour cloturer cette issue

**Comment by mathieuripert** [comment]
@carsso @colinemarie je peux prendre l'issue

**Comment by mathieuripert** [comment]
Checklist:
- [ ] add_columns `media_optin_at` and `visible_optin_at` to `vaccination_centers`
- [ ] add checkboxes in profil page
- [ ] add checkboxes in signup page

**Comment by carsso** [comment]
Si tu veux pas de souci pour moi !
Si jamais t'as pas le temps je la prendrai de toute façon quand j'arriverai au bout de ma Todo 😋

**Comment by colinemarie** [comment]
Ok 😊 Je pourrais refaire des choses qu'à partir de mardi !

**Comment by carsso** [comment]
@mathieuripert Tu as pris ou pas du coup ?

**Comment by carsso** [comment]
Fixed by #903
