### ISSUE TITLE
Redirection quand on est connecté en tant que PRO et qu'on va sur le lien /login

### ISSUE THREAD

**Issue by navidemad** [hostolab/covidliste#476]
## Contexte / Problème

Aucune redirection n'est faite quand on est déjà connecté et qu'on accède à l'url /login

## Priorité (Requis)

- `P3`: Pas prioritaire

**Comment by FelixMalfait** [comment]
Je ferme car ça fonctionne bien de mon côté (ça a peut-être été fait entre temps :))
