### ISSUE TITLE
Champ téléphone inscription pour vaccination

### ISSUE THREAD

**Issue by navidemad** [hostolab/covidliste#477]
## Contexte / Problème

Quand on saisit comme téléphone un nombre à 9 digits par exemple. Qu'il m'indique qu'il soit invalide je comprend, mais je trouve ça bizarre qu'il est populate avec le format international, ne devrait-il pas juste remettre le téléphone initial sans formatage de notre part ?

<img width="462" alt="Screenshot 2021-04-17 at 22 52 39" src="https://user-images.githubusercontent.com/6686865/115126496-aded7880-9fcf-11eb-8e74-1331754deb7a.png">

<img width="464" alt="Screenshot 2021-04-17 at 22 50 04" src="https://user-images.githubusercontent.com/6686865/115126478-89919c00-9fcf-11eb-8a06-0385d02c4707.png">

## Proposition

Repopulate le numero de telephone comme il était en input sans formattage de notre part

## Priorité (Requis)

- `P3`: Pas prioritaire

**Comment by carsso** [comment]
Normalement ça devrait être mieux avec #452
Et là ton numéro n'est pas valide (on match avec les ranges vraiment réservées par les opérateurs)

**Comment by navidemad** [comment]
Nice je connaissais pas cette méthode de vérification par range intéressant.
Après là je mettais sur en avant le fait que ca change le champ, alors que de base il est pas valide.
Mais oui ta PR devrait fixer le soucis 💯

**Comment by carsso** [comment]
La vérification par range elle est incluse dans la lib utilisée par la gem Phonelib. Ils ont fait ça pour chaque pays, des grands malades.

Oui, c'est un comportement un peu bizarre. On est pas partis sur le fait de le remettre dans l'état d'origine en cas d'erreur.
J'avais proposé ce que tu suggères dans une autre PR, qu'on avait décidé de fermer et on a pris la proposition du formatage systématique, et effectivement, à la réflexion, c'était mieux. Il faut juste le rendre moins perturbant pour un humain.
