### ISSUE TITLE
Pouvoir indiquer des infos de disponibilité dans le compte utilisateur

### ISSUE THREAD

**Issue by jmdesp** [hostolab/covidliste#480]
## Contexte / Problème

Un certain nombre des utilisateurs refusent des rendez-vous car en fait ils ne sont pas disponible ce jour là.
Leur permettre d'indiquer leurs disponibilités dans leur compte utilisateur permettrait d'éviter de les matcher un jour où de tout façon ils ne sont pas disponibles.

## Proposition
Ajouter dans le compte utilisateur un tableau permettant de cocher les jours de la semaine où l'utilisateur est non disponible.
Permettre aussi l'ajout de dates, ou de périodes spécifiques de non disponibilité.
Vérifier cette donnée au moment d'établir les match afin d'éliminer directement les personnes non disponibles

## Priorité (Requis)
- `P3`: Pas prioritaire

**Comment by Florto** [comment]
Pour moi c'est beaucoup d'informations personnelles stockées. Si la personne est pas dispo, elle accepte pas, next. Et si finalement elle peut, ça évite trop de maintenance pour elle.

**Comment by FelixMalfait** [comment]
Oui je suis d'accord. Je pense que ça complexifierait pas mal de choses pour une valeur ajoutée assez faible (très peu maintiendraient correctement leur disponibilité à jour). Je me permets de fermer mais n'hésite pas pour d'autres suggestions :)
