### ISSUE TITLE
Supprimer l’adresse exacte de la base de données

### ISSUE THREAD

**Issue by Florto** [hostolab/covidliste#489]
Suite à décision actée, pour les `User`s :

- [ ] s’assurer que l’adresse est convertie en latitude et longitude par le frontend et approximée
- [ ] ajouter par le frontend un blur aléatoire de quelques centaines de mètres sur l’adresse approximée
- [ ] s’assurer que le frontend n’envoie que les infos lat/lon approximées et code postal au backend
- [ ] ne stocker en db que les lat/lon approximées et le code postal (valeur calculée avant randomization et approximation des coordonnées)
- [ ] changer la page édition utilisateur pour ajouter une minicarte qui positionne le pin à l’endroit de l’adresse approximée
- [ ] ajouter sur la page édition utilisateur un disclaimer qui explique que l’adresse présentée ici est une adresse approximée pour des raisons de sécurité et confidentialité.
- [ ] permettre la modification de l’adresse sur la page édition utilisateur avec le même processus que sur la page inscription
- [ ] supprimer les données d’adresse précises et affiliées actuellement en base

**Comment by mathieuripert** [comment]
**Inscription**
- [ ] 1. Obtenir lat/lon depuis l'autocomplétion Algolia
- [ ] 2. ajout d'un bruit random sur lat/lon (`approximate_coords` method) (peut être fait côté serveur IMO)
- [ ] 3. validation sur lat/lon 
- [ ] 4. async reverse geocoding pour obtenir les autres champs geo (city, zipcode, geo_context ...)

[**fallback**]: si lat/lon n'est pas renvoyé côté client (ex: Algolia down) alors renvoyer adresse côté serveur et geocoding inline pour obtenir lat/lon, puis découler les steps suivants


**Page Profil**
- [ ] Mini carte
- [ ] Disclaimer

**Data**
- [ ] Drop address column
