### ISSUE TITLE
Contacter les gens par mail pour garantir la pertinence de la base

### ISSUE THREAD

**Issue by Florto** [hostolab/covidliste#493]
## Contexte / Problème

Au fur et à mesure du temps la qualité de la base va se dégrader.

## Proposition
- [ ] Créer un champ « to_be_deleted_at » dans le profil utilisateur
- [ ] Créer un batch qui chaque nuit va sélectionner X personnes (X à définir) dont la date de dernière connexion est supérieure à 2 mois. L’utilisateur se voit positionné le to_be_deleted_at à J+7
- [ ] Envoyer par le batch à ces gens un mail avec un lien unique qui permet de confirmer qu’ils souhaitent rester dans la liste et informant que sans contact de leur part, ils seront supprimés au bout de 7 jours.
- [ ] Le lien devrait les auto-connecter et les positionner sur l’édition de profil
- [ ] Une fois cliqué le lien, mettre à jour le champ de dernière connexion et supprimer le « to_be_deleted_at »
- [ ] Penser à bien afficher le bandeau nouvelles CGU en cas de besoin sur cette page et mettre à jour au passage le champ date des CGU informées
- [ ] Créer un batch qui supprime to les to_be_deleted_at dont la date est dépassée.

**Comment by rchampourlier** [comment]
👍 

Quelques  propositions complémentaires : 

- Réduire la durée de dernière connexion pour flagger les utilisateurs "to be deleted" à 1 mois peut-être, 2 mois me semble long dans ce contexte
- On pourrait aussi proposer aux utilisateurs qui ne consultent ou confirment pas 3 ou 5 matches de supprimer leur compte avec ce système ?

**Comment by thegrif** [comment]
J'ai de l'expérience dans la gestion d'un système similaire à covidliste à New York. Nous avons essayé d'utiliser à la fois des courriels et des SMS pour demander aux individus s'ils avaient été vaccinés ou non.

Nous n'avons pas eu beaucoup de succès.

Nous avons finalement construit une intégration dans la base de données principale de l'État sur la vaccination. Cela nous a donné une visibilité beaucoup plus large sur la façon dont notre système réussit à faire vacciner les gens.

Quelque chose de similaire est-il possible ici?
