### ISSUE TITLE
Ajouter le zipcode dans la table des centres de vaccination

### ISSUE THREAD

**Issue by laetitiajumel** [hostolab/covidliste#497]
## Contexte / Problème

La table des centres de vaccination ne contient pas les code postaux, ce qui rend les analyses dans Blazer par code postal ou département compliquées. (Les addresses sont stockées mais il manque le code postal)

## Proposition

Ajouter une colonne avec le code postal, qui peut être facilement récupéré grâce à l'adresse du centre. 
Backfill la table des centres avec leurs code postaux.

## Priorité (Requis)

Ajouter un label `Priorité`

- `P3`: Pas prioritaire

**Comment by mathieuripert** [comment]
Done !
