### ISSUE TITLE
Ajout d'un CAPTCHA aux pages d'inscription et d'identification

### ISSUE THREAD

**Issue by gralperic** [hostolab/covidliste#499]
## Contexte / Problème

Les pages d'inscription et d'identification utilisateurs / partenaires ne sont pas protégées contre des attaques de type "bots". 
## Proposition

Ajouter une vérification de type CAPTCHA à chacune des pages.

## Priorité (Requis)

- `P1`: Urgent, à résoudre dans la journée

**Comment by adrienpoly** [comment]
il y a ça en place https://github.com/hostolab/covidliste/pull/380

**Comment by martindaniel4** [comment]
@adrienpoly ah? @gralperic - ca correspond à ce que tu pensais?

**Comment by gralperic** [comment]
Pour moi #380 <https://github.com/hostolab/covidliste/pull/380> ne protège
pas contre un attaquant qui scripte des inscriptions en masse, car il est
très facile de récupérer automatiquement le token invisible qui est
positionné dans le formulaire d'inscription.
Idem sur les pages d'identification.

**Comment by martindaniel4** [comment]
Ok compris. 

@gralperic tu recommandes quoi comme solution de Captcha ?

**Comment by gralperic** [comment]
La meilleure en terme d'expérience utilisateur c'est
https://www.google.com/recaptcha/about/ (reCAPTCHA v3, gratuit jusqu'à 1
million de requêtes par mois) mais on ne veut pas forcément utiliser tel
produit dans notre contexte. Je ne suis pas familier avec d'autres
solutions.

**Comment by martindaniel4** [comment]
Moi ça me va personnellement. Soit il y a une bien meilleure alternative en tech française, mais pour la gestion des Captcha, ça me va d'utiliser Google. Qu'en pensez vous @mathieuripert, @carsso, @mininao ?

**Comment by Florto** [comment]
Perso je suis très contre vu la montagne de merde qui s’est abattue sur stop covid quand ils l’ont utilisé. Idem avant pour le générateur d’attestation.

**Comment by martindaniel4** [comment]
@Florto quelles sont les raisons objectives à ne pas utiliser un Captcha Google? On ne passe pourtant pas de PII dans notre requête? Il s'agit juste d'un challenge..

**Comment by Florto** [comment]
Tout à fait, arguments aussi invoqués par stop-covid, mais c’était « oui mais ça fait communiquer un terminal avec les api google donc par tracking croisé donne de l’info à google. » Je peux pas dire que je sois 100% convaincu par cet argument, mais franchement, pour moi si on y va on va se prendre un monceau de reproches qu’on aimerait s’éviter. Des fois ça vaut le coup de s’acheter une tranquilité. Poke @carsso  pour son avis sur la question.

**Comment by martindaniel4** [comment]
Oui mais dans la balance bénéfice / risque, je suis d'accord avec @gralperic on devrait implémenter une solution de Captcha, c'est ça l'important. 

Et puis restons modeste Google sait déjà tout de tous les français, ils ont pas besoin de Covidliste 😏

**Comment by carsso** [comment]
En terme de cohérence pour moi ça ne va pas.
Jusqu'ici on a choisi uniquement des acteurs FR ou Européens pour tout.
Ça a été une peine à trouver, et même dans certains cas pour l'instant on à rien trouvé, cf cette discussion https://twitter.com/carsso/status/1383849843915845632.
Personnellement j'aime beaucoup les services de Google, mais vu tous les efforts jusqu'ici pour que aucune donnée ne passe par un service américain (excepté actuellement Twilio et une partie de Sendinblue), soit on décide que c'est ok de passer des datas sur des acteurs américains (ce qu'on à tout à fait le droit légalement), soit on reste comme on est et on reste cohérents et on doit trouver une alternative.

**Comment by adrienpoly** [comment]
Un utilisateur pour être confirmé doit valider son adresse mail. Cela rend très difficile pour un bot de scripter des sign up avec des adresses mails valides et ensuite de les confirmer.

Nous avons aussi le système [Rack Attack](https://github.com/hostolab/covidliste/pull/374) en place pour éviter des attack brut force sur le login. On pourrait étendre cela au sign up pour empêcher la même adresse IP de sign up X fois dans un temps donné.

Perso je ne vois pas l'intérêt de mettre un Captcha Google sauf avoir des emmerdes à la Tous Anti Covid

**Comment by gralperic** [comment]
Ok pour le sign-up mais le login n'est pas protégé des bots qui changent
d'IP en permanence (le plus courant).
Ok pour utiliser une lib Ruby plutôt que Google.

**Comment by adrienpoly** [comment]
Pour le sign in en complément de Rack Attack on propose d'implémenter https://github.com/hostolab/covidliste/issues/500

Si tu le sens PR welcome @gralperic

**Comment by martindaniel4** [comment]
(Si besoin on m'a aussi parlé de ces solutions- https://twitter.com/martindaniel4/status/1384172498070106120?s=21)

**Comment by adrienpoly** [comment]
La doc du Captcha AN si besoin
https://docs.ocapi.teklia.com/adding_on_website/#requirements

**Comment by mathieuripert** [comment]
Je ferme cette issue car nous allons implémenter une solution passwordless #512
