### ISSUE TITLE
Conserver hors-ligne les informations sur le match

### ISSUE THREAD

**Issue by MatthieuGariel** [hostolab/covidliste#510]
## Contexte / Problème

Nous affichons les informations sur le match confirmé à l'URL du match en question.
Ainsi, pour conserver les coordonnées, adresse du match, les personnes doivent rouvrir le match.
Si la connexion est mauvaise, ils ne pourront pas retrouver ces informations.

## Proposition

=> Générer un PDF téléchargeable ?
=> Générer un .ics enregistrable dans l'agenda ?
=> Toute autre solution permettant de conserver ces infos hors ligne

## Priorité (Requis)
P3

**Comment by navidemad** [comment]
Si on part sur la génération de PDF faut que ca soit faut client side avec une librairie JS type celui utilisé pour générer les attestations de déplacements, parce que si c'est server sided ça impliquera des coûts.

**Comment by MatthieuGariel** [comment]
@navidemad Je n'ai aucune religion sur le sujet.

- Le moins coûteux en ressources serait évidemment le mieux (le .ics pourrait l'être ?).
- On a également pensé à l'envoi d'un mail de confirmation (mais ça rajoute un mail de plus).

Mais devoir systématiquement rouvrir la page du match n'est pas forcément le plus clair/simple en terme d'UX.

Le débat est ouvert.

**Comment by rchampourlier** [comment]
Je mets en draft en attendant que la discussion sur la solution soit finalisée pour éviter de démarrer un dev avant.
