### ISSUE TITLE
Passwordless

### ISSUE THREAD

**Issue by mathieuripert** [hostolab/covidliste#512]
## Contexte / Problème

Implémenter une stratégie de login sans mot de passe pour les volontaires (`User`).
Pourquoi:
- approche + sécure
- enlève de la friction au moment de l'inscription. Pas besoin de choisir de mot de passe.
- permet de ne pas être exposé à des attaques de type "credential stuffing"

## Proposition

Plusieurs approches possibles:
- https://dev.to/matiascarpintini/magic-links-with-ruby-on-rails-and-devise-4e3o (tokens stockés en base)
- https://github.com/abevoelker/devise-passwordless (tokens chiffrés)

## Priorité (Requis)

Ajouter un label `Priorité`

- `P2`: Moyennement urgent, à résoudre en 4 jours

**Comment by mininao** [comment]
- Je pense que c'est une bonne idée, tout ce qui peut enlever de la friction !
- Je pense que vu que le login après inscription est utilisé de manière assez rare, finalement assez peu de personnes ont besoin d'un mot de passe, donc autant alléger le process
- Un contrepoint à explorer, serait que les volontaires non tech-saavy ne sont peut être pas habitués à ce genre de mécanismes.
- Pour ma grand-mère, avoir son mot de passe dans son carnet à mot de passe, ça reste rassurant, elle sait comment ça marche. Même si c'est pas sécurisé, c'est pas nous qui allons la faire changer, et de toute façon, le mot de passe de son mail est aussi dans le carnet.

**Comment by ssaunier** [comment]
Une gem potentielle pour l'implémentation : https://github.com/abevoelker/devise-passwordless

**Comment by navidemad** [comment]
Avec ma PR https://github.com/hostolab/covidliste/pull/533 L'édition de profil et la homepage, la partie de droite est la même. Du coup, je ferais :
1/ Retirer le champ mot de passe
2/ Autologer la personne sur l'édition de son profil quand il submit et mettre le message de succès en flash[:success] de sorte que si il s'est trompé sur le moment il puisse changer
3/ De plus on shoot un email à l'inscription avec un lien pour accéder à son compte qu'il pourra recliquer X fois depuis son mail

De toute façon maintenant qu'on a retiré le prénom, le nom et l'adresse postale exacte de l'édition de profil, il ne reste que le numéro de téléphone et l'adresse email.

Je pense que le gain est intéressant en terme de simplicité vs le risque d'exposer le num et l'adresse email de la personne si quelqu'un arrive à récupérer le lien de connexion de la personne.

**Comment by adrienpoly** [comment]
Je vais tenter une PR sur cette issue

**Comment by rchampourlier** [comment]
> 2/ Autologer la personne sur l'édition de son profil quand il submit et mettre le message de succès en flash[:success] de sorte que si il s'est trompé sur le moment il puisse changer
> 3/ De plus on shoot un email à l'inscription avec un lien pour accéder à son compte qu'il pourra recliquer X fois depuis son mail

@navidemad du coup on passe pas par une étape de confirmation d'email ? Ça peut être bien de garder ce flow là non, la confirmation lui permet de se logguer, comme tu le suggères (le token peut servir X fois), mais ça me parait pas mal de garder l'info que l'user est non confirmé s'il s'est trompé d'email. 

Le risque c'est qu'il se soit trompé d'email et qu'il ne s'en rende pas compte. Il ferme son browser et il ne pourra jamais revenir, et pour nous c'est un user confirmé, non ?

**Comment by navidemad** [comment]
ouais clairement il faut pas l autologuer tu as raison, la PR en cours d'adrien le faut très bien.
