### ISSUE TITLE
Empêcher les partenaires d'ajouter un centre avec une addresse incomplète

### ISSUE THREAD

**Issue by mininao** [hostolab/covidliste#515]
## Contexte / Problème

* Il y a beaucoup d'erreurs de saisies de l'addresse des centres, et surtout de ville manquante

## Proposition

* Bloquer la soumission du form tant qu'une ville n'est pas renseignée

**Comment by navidemad** [comment]
Je regarde, en plus c'est bizarre Algolia affiche France, quand on met une adresse en Guadeloupe par exemple.
Je prend.

**Comment by navidemad** [comment]
Deux PR sont en cours de review
