### ISSUE TITLE
Impossible de modifier les types de vaccins d'un centre

### ISSUE THREAD

**Issue by MatthieuGariel** [hostolab/covidliste#516]
## Contexte / Problème

Après qu'un centre est créé, on peut modifier le type de vaccin qu'il propose.
La modification du type de vaccin n'est disponible que pour les admins.

Le formulaire de modification du centre de vaccination n'enregistre pas les changements des types de vaccin.
Exemple :
- centre sélectionné puis "éditer le centre"
- j'ai décoché "Moderna", puis "Modifier le centre"
- petite alerte bootstrap "motifs bien enregistrées"

Mais la modif n'est pas prise en compte.

## Proposition

Bonne question !

## Priorité (Requis)
P2

**Comment by mininao** [comment]
(Je note que le formulaire à réparer est disponible pour les admins, pas pour les partenaires)
