### ISSUE TITLE
Exclure les fichiers statiques public/xxx.html de sonarcloud

### ISSUE THREAD

**Issue by navidemad** [hostolab/covidliste#521]
## Contexte / Problème

Dans le github action issue de sonarcloud, on se retrouve avec du duplicate code se trouvant dans les fichiers :
- public/404.html
- public/422.html
- public/500.html

Cependant ces fichiers sont full statiques donc c'est normal que de la duplication soit présente.

## Proposition

Apparament dans la config on peut rajouter des fichiers à exclure pendant l'analyse :

![e6088c1e7873a0744a5c8276834c211f6cf5edb2_2_1380x698](https://user-images.githubusercontent.com/6686865/115596435-640ad800-a2d8-11eb-808f-9d3dc2a1f664.png)

## Priorité (Requis)

- `P3`: Pas prioritaire

**Comment by mininao** [comment]
Je me permets de mettre ça en P3
