### ISSUE TITLE
User supprime son compte après avoir matché

### ISSUE THREAD

**Issue by MatthieuGariel** [hostolab/covidliste#527]
## Contexte / Problème

Vraisemblablement, des utilisateurs suppriment leurs comptes après avoir matché.
Nous ne conservons pas les données des utilisateurs après suppression du compte.
Ainsi, les partenaires voient s'afficher "3 matchs" mais les noms de 2 volontaires.

Je taggue @carsso qui a émis ce diagnostic.

Problème évoqué [ici](https://covidliste.slack.com/archives/C01TV9NDY5V/p1619093578088600)

## Proposition

- Empêcher de supprimer son compte si match en cours (même non validé)
- Afficher "user ayant supprimé son compte" pour les campagnes actuelles et antérieures

## Priorité (Requis)
P1/P2

**Comment by Florto** [comment]
Du coup est-ce qu’on pourrait pas plutôt avoir intérêt à dupliquer l’info user dans le match : 

Au moment de l’anonymisation, on anonymise le match et on vire le user.
Avant ça on marque le user pour surtout pas le rematcher.

**Comment by carsso** [comment]
@LauriePremel Je propose un passage en P1 car on a des récurrence et ça pose des soucis aux centres qui ont des gens validés qui suppriment leur compte et dons ils ne voient plus leurs corrdonnées

**Comment by carsso** [comment]
@Florto J'ai codé la proposition d'origine, ça parait un peu relou de devoir aller supprimer des infos a droite a gauche à chaque suppression de compte
