### ISSUE TITLE
Téléphone partenaire dans match confirmé

### ISSUE THREAD

**Issue by MatthieuGariel** [hostolab/covidliste#529]
## Contexte / Problème
Une fois le match confirmé, certains utilisateurs :
- ont besoin de précision sur les modalités du RDV (apporter des documents spécifiques)
- ont un empêchement, ont confirmé trop tôt et ne peuvent pas se rendre au RDV
- etc.

Le seul moyen de joindre le centre pour l'instant est de chercher sur Internet.
Si c'est une pharmacie, un cabinet médical, ils trouveront un numéro.
Si c'est un centre de vaccination, il est probable que ce numéro ne soit pas public, car temporaire.

=> Ils nous envoient un mail, souvent "simple" sans coordonnées, ni identifiants du match. Le temps perdu à leur demander de contacter le partenaire, le créneau du RDV est déjà passé.

## Proposition

Afficher, avec l'adresse, le numéro de téléphone du partenaire dans le match _**confirmé**._

⚠️ Bien utiliser le numéro du centre de vaccination (et pas celui de la personne qui a lancé la campagne).
⚠️ Vérifier que les partenaires autorisent la diffusion de ce numéro.
💡 Indiquer "en cas d'empêchement, vous pouvez joindre le partenaire à :"
💡 Le faire sous la forme d'un lien cliquable "tel:" ?

## Priorité (Requis)
P2

**Comment by navidemad** [comment]
Dans une campagne il y a un champ :extra_info
**Informations supplémentaires pour les volontaires**
_Accès, modalités... Les volontaires ne verront cette information qu’après avoir confirmé leur rendez-vous._

Peut-être utilisé cet encadré ?

**Comment by yann120** [comment]
Il faudrait voir si les centres de vaccination ont utilisés le champ :extra_info  pour communiquer leur numero ou non

Si on part sur la solution de communiquer le numero du centre de vaccination, ce que je trouve une bonne idée, comment pourrait-on prendre le consentement des centres ? 
Ajouter une checkbox dans un formulaire ? Vous avez une idée où ?

**Comment by MatthieuGariel** [comment]
@yann120 Je te réponds sur le base de comment on a réfléchi la chose hors Github. (et que j'ai discutée avec @navidemad aussi en privé)

Les centres ont rarement utilisé le champ :extra_info pour communiquer leur numéro, mais surtout "amenez votre Carte Vitale" ou "la 1ère porte à gauche", ce genre de précisions.

J'ai check, double check et triple check, on a expliqué en long, large et en travers aux centres que le numéro qu'ils inscrivaient dans :phone_number serait public, au cas où les personnes en auraient besoin.

Après, il faut strictement limiter l'affichage aux matchs confirmés.

Une discussion UI est en cours pour améliorer le match.
Je laisserai les plus informés rajouter où nous en sommes (dont @mininao).

**Comment by yann120** [comment]
Ok top! 👍
Dans ce cas, go pour le mettre le numéro dans l'email ?
Je peux m'en occuper aujourd'hui 🙂

**Comment by rchampourlier** [comment]
J'ai l'impression que c'est résolu par la PR #581
