### ISSUE TITLE
Créer une page pour les entreprises partenaires/qui nous soutiennent sur le site

### ISSUE THREAD

**Issue by carsso** [hostolab/covidliste#537]
## Contexte / Problème

Pour remercier toutes les entreprises qui nous soutiennent en nous mettant à disposition des ressources, leur créer un espace de visibilité sur le site

## Proposition

Une page avec le logo et le lien de chaque entreprise, une petite description. Eventuellement le sujet sur lequel elles nous soutiennent.

**Comment by yann120** [comment]
Est-ce qu'il serait possible d'avoir une liste de toutes ces entreprises ? Et si possible les logos ? 😎

**Comment by rchampourlier** [comment]
Issue en attente de plus d'infos

**Comment by carsso** [comment]
Ça va bouger très bientôt.

**Comment by carsso** [comment]
Fixed by #740
