### ISSUE TITLE
Améliorations UX profil utilisateur

### ISSUE THREAD

**Issue by mininao** [hostolab/covidliste#543]
## Contexte / Problème

* Toutes les fonctionnalitées sont mélangées/non hiérarchisées sur la page. Cela génère de la confusion.
* L'adresse est vide par défaut, ce qui donne l'impression qu'on ne connait pas la localisation du user
* Cela génère des contacts supports car cette page est visible juste après l'inscription

## Proposition

* Par défaut le profil est en mode "show" et on peut le passer en mode "edit" pour changer date de naissance ou Adresse. Ca permet de cacher le champ addresse vide par défaut. (bigup @MatthieuGariel pour la proposition)

**Comment by MatthieuGariel** [comment]
D'autre part, je pense qu'on peut modifier + raccourcir le texte suivant :
<img width="771" alt="Screenshot 2021-04-23 at 11 32 31" src="https://user-images.githubusercontent.com/52251307/115851850-b575ad00-a427-11eb-9327-1c4f3e8a85a2.png">


« Afin de conserver le moins de données personnelles, nous stockons votre adresse sous la forme de coordonnées GPS  (latitude/longitude) avec un paramètre aléatoire à +/- 100 mètres. » ou équivalent.

Et comme le dit @mininao, le bas de la page est un vrai fouillis :
- mettre [Télécharger mes données] dans un bouton ?
- supprimer les textes "vous voulez supprimer votre compte ?" "vous souhaitez télécharger vos données ?"
- le bouton "se déconnecter" est clair mais redondant avec la déconnexion par la navbar (moins facile d'accès)

![image](https://user-images.githubusercontent.com/52251307/115853084-0d60e380-a429-11eb-8945-98fd7a1a3769.png)

**Comment by mininao** [comment]
J'ajoute :
* Ca peut être cool d'afficher les stats Covidliste ici, pour pas avoir besoin de se déco pour les voir. (voir issue https://github.com/hostolab/covidliste/issues/438)
