### ISSUE TITLE
Ajout disclaimer à propos du "Prénom/Nom non demandé à l'inscription"

### ISSUE THREAD

**Issue by mathieuripert** [hostolab/covidliste#545]
## Contexte / Problème

Suite à #268 , le nom/prénom n'est plus demandé à l'inscription, mais seulement au moment du match.
Pour les volontaires déjà inscrits nous allons effacer leur nom/prénom. Par conséquent, certains volontaires ne vont pas comprendre pourquoi on leur demande nom/prénom  une seconde fois.

## Proposition

- Ajout d'un item dans la FAQ
- Ajout d'un petit disclaimer sur la page du match `pending`.

## Priorité (Requis)

Ajouter un label `Priorité`

- `P2`: Moyennement urgent, à résoudre en 4 jours

**Comment by mathieuripert** [comment]
Pour rappel voici la page du match
<img width="987" alt="Screenshot 2021-04-23 at 15 30 01" src="https://user-images.githubusercontent.com/128908/115878384-c84ca980-a448-11eb-8aba-e1fdd4035d81.png">

**Comment by Florto** [comment]
Proposition de wording. N’hésitez pas à modifier pour clarifier / simplifier / … 


Disclaimer personne qui n’a jamais mis son nom
```
Par mesure de sécurité, votre nom et prénom ne sont demandé qu’au moment où vous confirmez la proposition de rendez-vous. Plus d’infos ici => lien faq dans un nouvel onglet au clic
```
(faut-il rajouter / remettre ici que ça sera utilisé pour être revérifié ?

Disclaimer personne qui avait mis son nom
```
Lors de votre inscription, vous nous avez fourni vos noms et prénoms.

Cependant, pour des raisons de sécurité et de protection des données, nous avons pris la décision de ne pas conserver cette information tant que vous êtes en attente.

Par conséquent, nous vous les demandons à nouveau pour pour pouvoir confirmer le rendez-vous qui vous est faite.
```

FAQ

```
Pourquoi mon nom n’apparaît-il plus dans mon espace personnel ?
J’ai déjà fourni les informations de nom et prénom, pourquoi l’application me les redemande-t-elle pour confirmer mon rendez-vous ?

Dans notre optique de respect de votre vie privée et pour augmenter le niveau de sécurité, nous revoyons régulièrement nos règles d’utilisation.

Dans ce cadre, nous avons pris la décision de ne plus conserver les informations de nom et prénom des personnes inscrites sur CovidListe.

Pour permettre la validation de votre identité, vous serez invité à renseigner ces informations lors de l’acceptation d’une proposition de vaccination.
Soyez vigilant lors de la saisie de ces informations, le professionnel de santé les vérifiera ainsi que votre âge.
```

```
