### ISSUE TITLE
Modifier email & SMS de matching

### ISSUE THREAD

**Issue by LauriePremel** [hostolab/covidliste#547]
## Contexte / Problème

De nombreuses personnes matchées se rendent à leur RDV sans l'avoir validé au préalable. Les centres se trouvent donc avec un flow de personnes dont le rdv n'a pas été confirmé et donc les refusent.

Objectif : modifier les sms et mails et matching + page de confirmation afin de réduire les incompréhensions.  

## Proposition

- Wording Email de matching : 

Sujet du mail : "Une dose de vaccin est disponible, réservez-la vite."

Bonne nouvelle !

 Un vaccin NOM DE VACCIN est disponible près de chez vous. Réservez-le vite en cliquant sur le lien suivant :
 LIEN-Je réserve mon vaccin-

Si le lien ne fonctionne pas, copiez et collez l’adresse suivante dans votre navigateur :
 -LIEN-

Si vous souhaitez vous désinscrire de Covidliste cliquez sur ce lien :
 -LIEN-

- Wording SMS : 
Bonne nouvelle, une dose de vaccin vient de se libérer près de chez vous. Réservez-la vite sur : https://covidliste.com/sms/xxxxxxxxxxxxxxxxxxxxxxxx/email

## Priorité (Requis)

Ajouter un label `Priorité`

- `P0`: Incident qui doit être résolu immédiatement
- `P1`: Urgent, à résoudre dans la journée
- `P2`: Moyennement urgent, à résoudre en 4 jours
- `P3`: Pas prioritaire

**Comment by yann120** [comment]
I can work on this one

**Comment by yann120** [comment]
@LauriePremel Cela veut dire qu'on supprime la partie "Si vous ne le reservez pas avant ..., le vaccin sera attribué à un autre" ?

pour le `Si vous souhaitez vous désinscrire de Covidliste cliquez sur ce lien :` est-ce que ça serait ok de le mettre dans tout les footers des emails ? 
Il faudrait créer un lien pour la désinscription du coup ? => Peut être a faire dans un autre ticket ?

**Comment by LauriePremel** [comment]
@yann120  il semble que @mininao soit sur le sujet, tu confirmes @mininao ? 
Il faut effectivement rajouter un lien de désinscription sur ce mail, qu'il faudra déployer sur le reste des emails => https://github.com/hostolab/covidliste/issues/424

**Comment by mininao** [comment]
J'ai pris la PR de @yann120 du coup, il m'a devancé :)

**Comment by yann120** [comment]
Haha mince je n’avais pas vu que tu étais dessus 🙈 
Je peux pas m'assigne des issues ou ajouter des labels sur mes PRs
Je pense qu'il doit me manquer des droits 😅

**Comment by mininao** [comment]
C'est bon c'est shippé, merci Yann !
