### ISSUE TITLE
Refuser le match si l’utilisateur se supprime

### ISSUE THREAD

**Issue by Florto** [hostolab/covidliste#548]
## Contexte / Problème

Si un user  se supprime à réception d’un match, on doit refuser le match

P1  car peut améliorer le match rate.

**Comment by manzan46** [comment]
👋🏻j'ai ouvert une PR pour cette issue https://github.com/hostolab/covidliste/pull/693 feedback welcome :)

**Comment by manzan46** [comment]
Cette issue peut être close :)
