### ISSUE TITLE
Create a seed

### ISSUE THREAD

**Issue by yann120** [hostolab/covidliste#549]
## Contexte / Problème

When setting up the database, it takes a lot of time to setup an environment : 
create a User, to validate with (confirmed_at...), a partner...

## Proposition

Create a DB seed, so developers could have a DB populated when starting to contribute

## Priorité (Requis)

Ajouter un label `Priorité`

P3

**Comment by navidemad** [comment]
There is the populate rake task who create bunch of users, and one vaccination center.
I think this rake task may be need to be developed more

**Comment by yann120** [comment]
Ok Nice!
Maybe We could extract the code of this rake task to use it in the rake task and in the seed ?
Where should we extract it ? In a helper ? A service ?

**Comment by omontigny** [comment]
Hello, 
As newbie,  I maybe I can try this . 
I just noticed something in the rake task : there is an error on password field
actually the users table hasn't password field .
