### ISSUE TITLE
Chasse aux N+1 sur la page profile

### ISSUE THREAD

**Issue by adrienpoly** [hostolab/covidliste#582]
## Contexte / Problème

Pas mal de call à la DB sur la page `/profil`

![Capture d’écran 2021-04-26 à 6 59 02 AM](https://user-images.githubusercontent.com/7847244/116031003-205bf980-a65d-11eb-9dcf-638e70b7d7a3.jpg)

## Proposition

Suggestions de solutions à tester
- mémoiser 
- includes(:roles)
- installer en dev bullets ou prosopite pour détécter les N+1 plus facilement

## Priorité (Requis)

Je n'ai pas de notion de l'importance devops, j'ai l'impression que le site répond toujours très rapidement donc cela ne doit pas être critique non plus. Je laisse les personnes ayant une vue plus DevOps attribuer une priorité.

**Comment by rchampourlier** [comment]
@adrienpoly je retire le tag "Performance" pour l'instant pour réduire le nb de labels et j'ai ajouté "Tech" à la place
