### ISSUE TITLE
Ajouter Failure reason dans le match

### ISSUE THREAD

**Issue by Florto** [hostolab/covidliste#584]
## Contexte / Problème

Stocker l’origine de l’erreur de confirmation dans le match pour savoir mieux gérer et affiner si l’overbooking est trop fort entre autre.

- [ ] ajouter le champ dans le modèle (https://github.com/hostolab/covidliste/blob/324b7830a799700eca479376d1e9ded0048ed590/app/controllers/matches_controller.rb)
- [ ] dans le controller ajouter le remplissage en cas d’erreur

on stocke déjà la date de failure.

P1

**Comment by adrienpoly** [comment]
on stock le nom de l'erreur brut par exemple `Match::MissingNamesError`

**Comment by Florto** [comment]
ça me choque pas :) ça nuit pas à l’anonymisation et donne pas mal d’infos déjà
