### ISSUE TITLE
Modifier le texte de la FAQ

### ISSUE THREAD

**Issue by LauriePremel** [hostolab/covidliste#590]
## Contexte / Problème

Dans le cadre de la modification de l'algo de notification, on doit modifier le texte de la FAQ pour garder la transparence

## Proposition

FAQ>Fonctionnement>Par quel moyen vais-je être contacté? : 
“Si une dose de vaccin est disponible près de l’adresse que vous avez renseignée, nous vous enverrons un e-mail afin que vous puissiez confirmer votre disponibilité et réserver le vaccin. S’il reste des doses non attribuées à la fin de journée, nous vous recontacterons par SMS. Soyez donc le plus réactif possible dès que vous recevez un e-mail de notre part.”

## Priorité (Requis)

Ajouter un label `Priorité`

- `P0`: Incident qui doit être résolu immédiatement
- `P1`: Urgent, à résoudre dans la journée
- `P2`: Moyennement urgent, à résoudre en 4 jours
- `P3`: Pas prioritaire

**Comment by mininao** [comment]
Done
