### ISSUE TITLE
ActiveJob -> Sidekiq

### ISSUE THREAD

**Issue by mathieuripert** [hostolab/covidliste#604]
## Contexte / Problème

We use ActiveJob for our async jobs

## Proposition

Move to sidekiq jobs to unlock more configuration options like `retries_count`

## Priorité (Requis)

Ajouter un label `Priorité`

- `P2`: Moyennement urgent, à résoudre en 4 jours

**Comment by navidemad** [comment]
Si on passe à la version 6 de sidekiq, tu peux utiliser **sidekiq_options** dans les ActiveJob pour définir ton retries_count.
https://github.com/hostolab/covidliste/issues/432

**Comment by gearnode** [comment]
@navidemad Effectivement. Mais ActiveJob est beaucoup plus lent et consume beaucoup plus de RAM que Sidekiq.

**Comment by mathieuripert** [comment]
@navidemad @gearnode si c'est plus simple d'upgrade sidekiq faisons ça d'abord
