### ISSUE TITLE
Upgrade to bootstrap 5

### ISSUE THREAD

**Issue by mininao** [hostolab/covidliste#609]
## Contexte / Problème

* Il y a un mismatch entre la gem Bootstrap 5 et Bootstrap 4 dans le package.json
* On utilise à priori bootstrap 4, et certaines features de bootstrap 5 pourraient nous êtres très utiles (Responsive font sizes, radio toggle buttons)

## Proposition

Passer à bootstrap 5

**Comment by navidemad** [comment]
Ca veut dire au revoir IE, j'ai peur qu on perd une audience.
As-t on des statistiques sur les navigateurs utilisées ?

**Comment by adrienpoly** [comment]
Responsive font sizes est déjà disponible avec BS4

**Comment by adrienpoly** [comment]
Pour activer RFS https://getbootstrap.com/docs/4.4/content/typography/#responsive-font-sizes

par contre l’issue reste valide, il y a un mix entre BS4 (gem) et BS5 (package json).

**Comment by mininao** [comment]
* Très bon point sur IE, il faut peut-être rester sur BS4
* Trop cool pour RFS, je savais pas, je vais voir pour l'activer

Je pense qu'on va virer BS5 du coup.

**Comment by navidemad** [comment]
> par contre l’issue reste valide, il y a un mix entre BS4 (gem) et BS5 (package json).

C'est le contraire bootstrap 4 sur les gems et bootstrap 5 sur les packages
Pourquoi avons nous besoin du bootstrap via les gems ? Pourquoi pas juste le charger via webpacker ?
Vu qu'on passe par simple_form dans tous les cas.

**Comment by mininao** [comment]
> Pourquoi avons nous besoin du bootstrap via les gems ?

Je sais même pas, on peut surement le virer du coup 🤷

**Comment by colinemarie** [comment]
Je fais un petit tour des issues, est-ce que vous aviez décidé quelque chose @adrienpoly @mininao @navidemad  ?

**Comment by mininao** [comment]
Yes, il faut retirer bootstrap 5 des gems
