### ISSUE TITLE
Ajouter une mention sur la page de campagne des centres de vaccination

### ISSUE THREAD

**Issue by ardjo-s** [hostolab/covidliste#617]
## Contexte / Problème

Certains professionnels de santé re-créé une campagne de vaccination parce que celle en cours ne se remplit pas suffisamment vite. ->  Fausse le tracking des campagnes.

## Proposition

Ajouter une mention sur la page de la campagne active du professionnel de santé sous les indicateurs de la campagne :
"Important : Si vous avez l’impression que la campagne ne se remplit pas, ne créé pas une nouvelle campagne pour les mêmes doses disponibles. Nous recontacterons par sms tous les volontaires le proche de votre centre s’il vous reste des doses au cours de l’après-midi." 

Précision : "Nous recontacterons par sms tous les inscrits le plus proche de votre centre" en lien qui renvoie sur la FAQ.
![covidliste - partenaires - suivi](https://user-images.githubusercontent.com/10088552/116270648-922c6400-a77f-11eb-8426-91c3167f4e0f.png)

## Priorité (Requis)
'P2'

- `P0`: Incident qui doit être résolu immédiatement
- `P1`: Urgent, à résoudre dans la journée
- `P2`: Moyennement urgent, à résoudre en 4 jours
- `P3`: Pas prioritaire

**Comment by Segolene-Alquier** [comment]
Hello, je peux prendre cette issue? 🤓
