### ISSUE TITLE
Ajouter un mime part text pour chaque email

### ISSUE THREAD

**Issue by gearnode** [hostolab/covidliste#660]
## Contexte / Problème
Nous envoyons des e-mails avec seulement une mime part `html`. Certains ISP bloque les e-mails quand ils n'ont pas de mime part `text`.

## Proposition
Ajoutée une mime part `text` a tous nos e-mails.

**Comment by navidemad** [comment]
Je rajouterais que selon https://www.mail-tester.com
> Your message should contain an <html> tag
> Message only has text/html MIME parts
> You should also include a text version of your message (text/plain)

**Comment by Intrepidd** [comment]
https://github.com/fphilipe/premailer-rails/ permet la génération automatique de text part.

Si ca vous va comme approche je veux bien m'en occuper, vous pouvez m'assigner l'issue ?
