### ISSUE TITLE
Réduire le bruit Appsignal

### ISSUE THREAD

**Issue by mininao** [hostolab/covidliste#665]
## Contexte / Problème

* Appsignal remonte énormément d'erreurs, ce qui ne nous permet pas de l'utiliser pour nous alerter.

## Proposition

* Muter les erreurs fréquentes et non importantes
* Régler les erreurs fréquentes

**Comment by navidemad** [comment]
<img width="770" alt="Screenshot 2021-04-30 at 21 26 39" src="https://user-images.githubusercontent.com/6686865/116744580-cb243d00-a9fa-11eb-831a-84e7701e4819.png">

Je vois qu'on pourrait exclure :
- Net::ReadTimeout: Net::ReadTimeout with #<TCPSocket:(closed)>
- ActionController::BadRequest: Invalid query parameters: invalid %-encoding 

Le reste en vrai ca flood mais c'est des cas d'erreurs à gérer, les muter je suis pas sur que ca va arranger les chose.
