### ISSUE TITLE
Permettre aux utilisateurs ayant refusé un match de se désinscrire / modifier leurs infos

### ISSUE THREAD

**Issue by MatthieuGariel** [hostolab/covidliste#674]
## Contexte / Problème

Nous avons empêché [ici](https://github.com/hostolab/covidliste/issues/527) à l'utilisateur de supprimer son compte après avoir confirmé un match.

Seulement, nous avons également bloqué la possibilité pour les matchs non confirmés, de modifier ou supprimer leur compte.

Les matchs n'ayant plus d'expiration dans l'algorithme v2, certains comptes pourront rester bloqués plusieurs heures.

Nous bloquons cette possibilité même s'ils ont refusé le RDV par le bouton "Refuser" sur le match. [discuté ici](https://covidliste.slack.com/archives/C01TYASR1DX/p1619705393358100?thread_ts=1619702612.355700&cid=C01TYASR1DX)

## Proposition

Permettre au match non confirmé/match refusé de pouvoir modifier/supprimer son compte.

## Priorité (Requis)
- `P2`: Moyennement urgent, à résoudre en 4 jours
- `P3`: Pas prioritaire

**Comment by MatthieuGariel** [comment]
@rchampourlier Je pense que ça rentre dans ce milestone ? https://github.com/hostolab/covidliste/milestone/4

**Comment by manzan46** [comment]
https://github.com/hostolab/covidliste/pull/710 PR ouverte, feedback welcome. 

> Permettre au match non confirmé/match refusé de pouvoir modifier/supprimer son compte.

❓ en regardant le code je suis pas sure que c'etait le cas pour match refusé

**Comment by rchampourlier** [comment]
@MatthieuGariel tout à fait (désolé pour le lag)

Je ferme, implémenté par #710 🎉
