### ISSUE TITLE
Mise à jour automatique des gems avec `dependabot`

### ISSUE THREAD

**Issue by GuillaumeWrobel** [hostolab/covidliste#679]
## Contexte / Problème

Des mises à jour critiques de sécurité peuvent être nécessaires. Dependabot est un outil qui soumet des Pull Request lors d'une mise à jour.

La suite de test permettra de capter certaines erreurs mais on ne doit pas relâcher notre vigilance après un update.

## Proposition

Un admin du repo comme Mathieu doit s'authentifier sur https://app.dependabot.com/

## Priorité (Requis)

- `P3`: Pas prioritaire

**Comment by EmCousin** [comment]
Je pose ça ici : https://twitter.com/chriscoyier/status/1376323252084178944

Des développeurs ont observé des tentatives de piratage à partir de Pull Requests usurpant le nom de DependaBot.
J'aviserais simplement de bien regarder que les PRs de dependabot sont bien authentiques avant de les merger. J'utilise moi-même Dependabot pour mes projets persos et avais tendance jusqu'ici à faire confiance et à merger sans trop regarder.

**Comment by jarthod** [comment]
Pour info la nouvelle version de Dependabot intégré nativement à Github s'active maintenant depuis https://github.com/hostolab/covidliste/settings/security_analysis directement (pour un admin).
