### ISSUE TITLE
Optimisation du pagespeed / SEO

### ISSUE THREAD

**Issue by adrienpoly** [hostolab/covidliste#682]
## Contexte / Problème

le page speed est l'un des critères utilisé par Google pour son ranking

Actuellement le Page Speed de la home en mobile est pas ouf

https://developers.google.com/speed/pagespeed/insights/?hl=fr&url=www.covidliste.com&tab=mobile

<img width="814" alt="Screenshot 2021-05-06 at 10 40 51" src="https://user-images.githubusercontent.com/128908/117268487-9a5b6200-ae57-11eb-9f8f-8887da49405c.png">

On peut aussi aller plus loin avec les recommandations Lighthouse

## Proposition

Prendre les points majeur du report et essayer d'obtenir min >90

![Capture d’écran 2021-04-30 à 7 03 24 AM](https://user-images.githubusercontent.com/7847244/116650775-2fef8100-a982-11eb-8bb9-9a448e6b2e1c.jpg)

- optimiser les pack JS de la home
- optimiser les images 

## Priorité (Requis)

Ajouter un label `Priorité`

- `P2`: Moyennement urgent, à résoudre en 4 jours
- `P3`: Pas prioritaire

**Comment by GuillaumeWrobel** [comment]
Pour les images, il y a : https://github.com/hostolab/covidliste/pull/677

**Comment by adrienpoly** [comment]
oui #677 va aider mais pour la home l'optimisation des images c'est un cran au dessus. 

Pour le tel par exemple il faut avoir une dimension plus proche du rendu final et surtout avoir 2 versions différente pour le 1x et 2x (et cerise sur le gateau une version webp)

![Capture d’écran 2021-04-30 à 9 01 06 AM](https://user-images.githubusercontent.com/7847244/116659937-9c727c00-a992-11eb-933b-855720d7532d.jpg)
