### ISSUE TITLE
Compteur pour le nombre d'inscrits / contactés / confirmés

### ISSUE THREAD

**Issue by mathieuripert** [hostolab/covidliste#698]
## Contexte / Problème

![Screenshot 2021-05-01 at 10 47 53](https://user-images.githubusercontent.com/128908/116776778-b1224300-aa6a-11eb-9bc6-1e0fb51ebf10.png)

Deux problèmes:
1. On affiche seulement le nombre total de users actuellement inscrits (User.count) ce qui est en dessous du nombre total d'inscrits depuis le début, à cause des suppressions de comptes ("select max(id) from users" peut être un bon point départ mais n'est pas assez safe)
2. On veut mettre en cache ces requêtes pour éviter de spammer la BDD à chaque visite (on utilise déjà redis cache)

## Proposition

- Créer une table `counters` qui permet de compter les nombre total d'inscrits, de matches, de matches confirmés.
- Mettre en place des callbacks permettant de mettre à jour ces compteurs
- Requeter cette table pour afficher les stats sur la home

## Priorité (Requis)

Ajouter un label `Priorité`
- `P2`: Moyennement urgent, à résoudre en 4 jours

**Comment by tildedash** [comment]
Bonjour, 

Est-ce que les callbacks n'ajouteront pas un volume d'écriture trop importants sur la DB ?

**Comment by Intrepidd** [comment]
Avec des bons index et du cache agressif on pourrait peut-être se passer de la table de counter ? 

Je veux bien prendre cette issue

**Comment by mathieuripert** [comment]
> Avec des bons index et du cache agressif on pourrait peut-être se passer de la table de counter ?
> 
> Je veux bien prendre cette issue

En fait c'est surtout pour le compteur du nomnbre total d'inscrits car on perd les users qui suppriment leur compte (on supprime vraiment les users!)

**Comment by mathieuripert** [comment]
> > Avec des bons index et du cache agressif on pourrait peut-être se passer de la table de counter ?
> > Je veux bien prendre cette issue
> 
> En fait c'est surtout pour le compteur du nombre total d'inscrits car on perd les users qui suppriment leur compte (on supprime vraiment les users!)

mais du coup on a déjà qqchose ici -> https://github.com/hostolab/covidliste/blob/master/app/models/counter.rb#L1
