### ISSUE TITLE
Augmenter le ratio "RDV confirmés / nombre d’inscrits contactés“.

### ISSUE THREAD

**Issue by EmeFin** [hostolab/covidliste#699]
## Contexte

Constat : le ratio entre le nombre de rendez-vous confirmés (un total de 6284 au 01.05.2021 14h30) et le nombre d’inscrits contactés (111 851, à la même date, même heure) est relativement bas (5,6%).

## Proposition

Proposition destinée à augmenter le ratio "nombre d’inscrits contactés vaccinés (RDV confirmés) / nombre d’inscrits contactés“. 

Idée de base : faire savoir à la personne volontaire à la vaccination inscrite sur covidliste.com (l’inscrit) en fonction des données la concernant (âge, lieu de résidence) et de la disponibilité des doses de vaccin dans son secteur, la probabilité qu’elle a de devenir prochainement un „inscrit contacté“ afin:
- de lui éviter de passer à côté de la notification à laquelle elle doit réagir très rapidement, et finalement,
- d’augmenter ses chances d’être vaccinée via covidliste.com.

Quelques suggestions...

On alloue à l’inscrit un rang de priorité, principalement fonction de son âge et de son ancienneté dans covidliste.com, qui évolue (constamment à la baisse) avec le temps.

Dès que le rang de l’inscrit atteint la „taille"* du „groupe"**, l’inscrit reçoit une pré-notification l’incitant à vérifier dès à présent régulièrement le contenu de sa boite mail, en l’informant qu'il recevra probablement dans X jours une notification à laquelle il devra répondre rapidement.

La variable à prédire (date probable de notification = date d’envoi de la pré-notification + X jours) est à estimer en fonction de la taille du groupe et de la vitesse d’écoulement des vaccins dans le „secteur“*** au milieu duquel l’inscrit se situe géographiquement.

Ce nombre de jours X peut être déterminé comme étant le rapport entre la taille du groupe (par exemple 100 personnes) correspondant au secteur de l’inscrit, divisé par le nombre de doses mises à disposition des inscrits contactés s’étant fait vacciner dans le secteur de l’inscrit (par exemple 250 doses) dans un temps défini (par exemple au cours des 7 derniers jours).

Exemple:

- 250 doses dont les inscrits d’un secteur ont bénéficié en 7 jours = 36 doses / jour en moyenne.
- Si taille du groupe pour ce secteur est égale à 100, X = 100 / 36 = 2,8 jours.
- Date d’envoi de la pré-notification = date d’atteinte du rang 100 pour l’inscrit - 2,8 jours (67 heures).

Étant donné que les vitesses d’écoulement des doses (via covidliste.com) diffèrent (très probablement) grandement d’un secteur à un autre (vitesse d’écoulement plus rapide dans les grandes villes qu’en zone rurale), le paramètre „taille" du groupe sera à définir (constant ou variable) en fonction des secteurs / régions.
De plus, ces vitesses d'écoulement pouvant varier dans le temps, il conviendra de permettre aux paramètres décrits d'évoluer.

Je ne rentre pas plus dans les détails, histoire de ne pas rendre la proposition totalement obscure. 

**Aux algorithmiciens et aux codeurs de jouer ;-).**

(*) pour une région donnée, on définit une taille de groupe ; par exemple un groupe de 100 inscrits. La taille est fonction de la vitesse d’écoulement des doses. Plus celle-ci est importante, plus la taille du groupe devra l’être, le but étant de prévenir l’inscrit à contacter quelques jours avant la notification (par exemple 2 à 4 jours, tout le monde n’étant pas h24 devant sa tablette, son smartphone, son ordinateur).

(**) groupe de personnes sélectionnées en vue d’une vaccination probable dans X jours.

(***) le secteur est défini par une zone centrée sur l’adresse de l’inscrit englobant un certain nombre de centres de vaccination. Le secteur est plus petit dans les grandes villes que dans les zones rurales.

## Priorité (Requis)

- `P3`: Pas prioritaire ;-) - Mais merci de réfléchir au sujet, s'il vous paraît utile de le développer.

**Comment by rchampourlier** [comment]
Bonjour @EmeFin,

Merci d'avoir ouvert cette issue et pour ces suggestions ! Je lui ajoute le tag `draft` car s'il y a lieu d'avancer dessus, ça nécessitera un peu de discussion avec nos bénévoles experts en data, il y a déjà plusieurs pistes en cours d'exploration pour améliorer le matching, mais c'est une idée intéressante que d'avoir une pré-notification.

**Comment by mathieuripert** [comment]
Je close cette issue car il n'y pas d'action immédiate
