### ISSUE TITLE
Envoi de message sur un compte fermé

### ISSUE THREAD

**Issue by sthepaut** [hostolab/covidliste#720]
Le seul moyen de vous faire remonter le probleme utilisateur que je subit est via github alors allons-y.
J'ai supprimé mon compte sthepaut@free.fr depuis des semaines et je reçois toujours des messages pour des vaccins à proximité (tous est relatif car il s'agit tout de meme de 20 bornes).
Comme il est supprimé je ne peut plus me logger pour demander à le supprimer.
Merci donc de supprimer mon adresse de la liste et de fixer le bug par la même occasion.

**Comment by rchampourlier** [comment]
Bonjour @sthepaut,

Désolé que vous rencontriez ce problème, je vais regarder ce qu'il en est. Je vous recontacte par email pour poursuivre la discussion et je ferme cette issue en espérant que cela résolve votre problème.
