### ISSUE TITLE
[Partenaires] Clarifier le niveau de robustesse attendu du mot de passe

### ISSUE THREAD

**Issue by mathieuripert** [hostolab/covidliste#766]
## Contexte 

Le niveau de robustesse attendu du mot de passe pour l’inscription des partenaires n’est pas assez clair.
Sur le formulaire d’inscription, on indique le niveau du mot de passe (faible, moyen, robuste, très robuste) mais ce n’est pas évident de comprendre que le niveau attendu est au moins “robuste”.

## Proposition

Il faudrait avoir un “feed-back” beaucoup plus clair pour indiquer que la robustesse du mdr est suffisante ou non

## Priorité (Requis)

Ajouter un label `Priorité`
- `P2`: Moyennement urgent, à résoudre en 4 jours

**Comment by arnaudpeich** [comment]
Je regarde ça

**Comment by arnaudpeich** [comment]
J'ai ouvert une PR, mais une petite remarque : c'est un pattern que je n'ai rencontré nulle part ailleurs. Les indicateurs de robustesse ne sont généralement là qu'à titre indicatif, la règle pour accepter ou non un mot de passe est en général plus simple/explicite.

**Comment by mathieuripert** [comment]
> J'ai ouvert une PR, mais une petite remarque : c'est un pattern que je n'ai rencontré nulle part ailleurs. Les indicateurs de robustesse ne sont généralement là qu'à titre indicatif, la règle pour accepter ou non un mot de passe est en général plus simple/explicite.

Je crois que vous utilisez qq chose de similaire chez alan. C'est @mininao qui nous a suggéré la lib [zxcvbn](https://github.com/dropbox/zxcvbn) https://github.com/hostolab/covidliste/pull/483#pullrequestreview-638359068

**Comment by arnaudpeich** [comment]
> Je crois que vous utilisez qq chose de similaire chez alan. C'est @mininao qui nous a suggéré la lib [zxcvbn](https://github.com/dropbox/zxcvbn) [#483 (review)](https://github.com/hostolab/covidliste/pull/483#pullrequestreview-638359068)

Ah ah tu me l'apprends 😅  (je suis nouveau chez Alan ^^) Merci !
