### ISSUE TITLE
Impossible de modifier les données d'inscription (alors qu'il n'y a plus de match en cours)

### ISSUE THREAD

**Issue by ThePiloo** [hostolab/covidliste#767]
## Contexte / Problème

Impossible de modifier les données d'inscription (alors qu'il n'y a plus de match en cours) 

## Proposition

Corriger le dysfonctionnement en prenant en vérifiant que les matchs sont expirés ou refusés

## Priorité (Requis)

- `P2`: Moyennement urgent, à résoudre en 4 jours

**Comment by mininao** [comment]
Hello @ThePiloo ! Merci pour l'issue.
Peux-tu donner plus de détails sur le bug ? Je n'arrive pas à le reproduire.
Est-ce que tu as ce problème avec ton compte en prod ?

**Comment by mininao** [comment]
Je ferme l'issue pour l'instant, ne pas hésiter à réouvrir si y'a des nouvelles
