### ISSUE TITLE
Amélioration du CSV des volontaires disponible à chaque campagne

### ISSUE THREAD

**Issue by colinemarie** [hostolab/covidliste#775]
## Contexte / Problème

Le CSV actuellement disponible ne passe pas bien sur LibreOffice, il y a un problème les accents. Aussi il faudrait qu'il soit trié par ordre alphabétique et des noms puis des prénoms pour faciliter le travail du lieu de vaccination.
## Proposition

_Ebauche de proposition de solution(s)._

Voir pour inspiration ce qui a été fait pour le CSV dans la partie admin/vetting où il y avait déjà un bug d'accent

## Priorité (Requis)

- `P3`: Pas prioritaire

**Comment by carsso** [comment]
Plutôt P2, c'est un problème pour les centres que les noms soient pas bons (accents cassés) et pas triés

**Comment by FrancoisNarolles** [comment]
Suite discussions sur place avec l'un de nos plus gros centre, ils ont un gros besoin de pouvoir imprimer ça :
![image](https://user-images.githubusercontent.com/66469664/119170179-2d54e880-ba63-11eb-9d07-5624ab727a74.png)

François Narolles

**Comment by FrancoisNarolles** [comment]
Je soutiens l'escalade vers une priorité importante, notamment pour le bénéfice fidélisation de nos centres : ils nous disent un truc, on revient vers eux rapidement.
