### ISSUE TITLE
Ajouter vérification du formulaire de campagne

### ISSUE THREAD

**Issue by colinemarie** [hostolab/covidliste#777]
## Contexte / Problème

Cas de campagnes lancées après le créneau proposé, ce qui n'est normalement pas possible. Cela peut arriver lorsque que le professionnel laisse la fenêtre ouverte et valide le formulaire de lancement de campagne plus tard.

## Proposition

Faire un check des informations du formulaire lors du clic sur le bouton pour s'assurer que personne n'a laissé le formulaire traîner et que les informations sont toujours valides.

## Priorité (Requis)

Ajouter un label `Priorité`

- `P2`: Moyennement urgent, à résoudre en 4 jours

**Comment by arnaudpeich** [comment]
J'ai l'impression que c'est déjà le cas : [Formik valide automatiquement le formulaire au moment du submit](https://formik.org/docs/guides/validation#when-does-validation-run).

J'ai essayé localement et ça fonctionne bien chez moi.

**Comment by mininao** [comment]
Je crois que ça devrait être réglé, je garde un oeuil sur les campagnes 👀
