### ISSUE TITLE
Bloquer la création de campagne avec une plage de RDV sur 2 jours

### ISSUE THREAD

**Issue by colinemarie** [hostolab/covidliste#778]
## Contexte / Problème

Exemple d'une campagne
 `created_at: "2021-05-14 22:05:36.000004000 +0200"
starts_at: "2021-05-14 22:15:07.705000000 +0200"
ends_at: "2021-05-15 22:35:07.706000000 +0200"``

Or cela affiche ceci pour l'utilisateur comme nous ne faisons que des campagnes pour le jour même (sans afficher le jour)
![image](https://user-images.githubusercontent.com/68182973/118376395-fd6f9600-b5c7-11eb-954a-cd28aab465ed.png)

## Proposition

Vérifier que l'on bloque bien la création d'une campagne qui s'étale jusqu'a J+1 et que la conversion heure > date se fait bien.

## Priorité (Requis)

Ajouter un label `Priorité`

- `P2`: Moyennement urgent, à résoudre en 4 jours

**Comment by EmCousin** [comment]
@colinemarie Je suis sur la dernière version de `master`. J'ai juste quelques questions pour être sûr d'avoir bien compris le beoin.

Dans le formulaire de création de campagne pour les partenaires, il n'est poas possible de créer une campagne sur 2 jours.
- Est-ce que justement on veut changer ça aussi ?
- Est-ce que les campganes doivent désormais s'étaler sur 2 jours, ni plus, ni moins, pour tout partenaire souhaitant en créer une ?
- Y a t'il d'autres critères / limitations à prendre en compte ?

**Comment by colinemarie** [comment]
Je n'ai pas regarder en détail et je pensais effectivement comme tu le dis qu'il n'est pas possible de créer une campagne sur plusieurs jours. L'exemple dans l'issue est un problème remonté par @carsso , donc il doit avoir un bug quelque part qui a permis ça. Il faut peut-être investigué.

Dans tous les cas, on ne veut pas permettre une campagne sur plusieurs jours, ni en avance. Toutes les campagnes doivent être lancées le jour même pour le jour même.

**Comment by carsso** [comment]
J'ai aucune idée de comment ils ont réussi à faire ça. Mais ils ont réussi 🤣

**Comment by EmCousin** [comment]
Peut-être quelqu'un de malin qui a dû inspecter l'élément et entrer les valeurs à la main. Il n'y a pas de validation côté backend pour vérifier cette limite. Je suis en train de m'en occuper 🙂

**Comment by mininao** [comment]
Coucou, en fait y'a aucune validation en front que l'horaire de début est le même jour que l'horaire actuel, je crois que c'est "juste" ça le problème.

**Comment by mininao** [comment]
Je ferme l'issue car ça devrait être réglé, sur la partie front, par https://github.com/hostolab/covidliste/pull/837
