### ISSUE TITLE
Permettre l'affichage facultatif du téléphone du centre sur la page/mail de confirmation de match

### ISSUE THREAD

**Issue by colinemarie** [hostolab/covidliste#781]
## Contexte / Problème

Aujourd'hui les volontaires n'ont pas les moyens de joindre le centre s'ils doivent les prévenir pour quelconque raisons. Mais tous les lieux ne souhaitent pas forcément faire afficher le numéro.

## Proposition

- [ ] Proposer au professionnel dans le formulaire de création de campagne l'affichage facultatif du numéro du centre aux volontaires. 
- [ ] Faire afficher le numéro (si demandé par le centre) sur la page du match confirmed et dans le mail de récap de confirmation.

## Priorité (Requis)

Ajouter un label `Priorité`

- `P2`: Moyennement urgent, à résoudre en 4 jours

**Comment by arnaudpeich** [comment]
Hello, je peux essayer de m'en occuper mais j'ai une petite question : la page "campagne" est-elle bien le meilleur endroit pour proposer ce choix ?
Dans la mesure où le numéro de téléphone est une propriété du centre de vaccination, j'aurais bien ajouté le booléen sur la même table (et donc sur le formulaire de création/modification du centre).
Qu'en penses-tu ?

**Comment by colinemarie** [comment]
C'est ce que je m'étais dit aussi, on aurait pu l'intégrer à #780 lorsqu'on leur explique pourquoi nous en avons besoin au sein du formulaire d'inscription.
Mais nous avons déjà beaucoup de centres inscrits qui n'auront pas pas été confronté ce booléen. Donc je ne sais pas ce qui serait le mieux.  Peut-être qu'on se dit que pour tous ceux là, on décide que par défaut on ne l'affiche pas et qu'on met une petite indication dans la page de campagne "si vous souhaitez afficher votre numéro de téléphone pour les utilisateurs, cochez la case etc".
@carsso @MatthieuGariel un avis ?

**Comment by arnaudpeich** [comment]
Ok merci pour la clarification !

Je serais effectivement en faveur de l'affichage d'un message pour inviter les partenaires à accepter la diffusion de leur numéro aux utilisateurs si ce n'est pas déjà fait, plutôt en mode "warning" d'ailleurs, par exemple :

> Attention, votre numéro de téléphone ne sera pas communiqué aux utilisateurs pour cette campagne. Pour permettre sa diffusion, cliquez ici pour modifier les paramètres de votre centre de vaccination avant de créer votre campagne.

Pour aller plus loin (je ne sais pas dans quel mesure c'est simple à faire en Rails), on pourrait éventuellement mettre le champ sur la table des centres de vaccinations mais le rendre modifiable dans le formulaire de la campagne (il faudra juste là aussi un message expliquant bien que ce changement s'appliquera à toutes les campagnes). Je ne me lancerai pas là-dedans vu que je suis débutant en Rails, mais c'est une amélioration possible dans un deuxième temps.

------

Du coup je me lance dans la version où le champ est dans la table "centre de vaccination" et sur le formulaire associé. Ça me demandera de comprendre mieux comment fonctionnent les contrôleurs, les modèles et les migrations en Rails. Si finalement on décide de faire ça par campagne, ce sera simple à déplacer je pense.

**Comment by arnaudpeich** [comment]
Détail d'importance : pour faire ce que je propose, il faut ajouter un formulaire pour modifier un centre de vaccination déjà créé (seuls les admins en ont un pour le moment, à ma connaissance)

**Comment by colinemarie** [comment]
> Détail d'importance : pour faire ce que je propose, il faut ajouter un formulaire pour modifier un centre de vaccination déjà créé (seuls les admins en ont un pour le moment, à ma connaissance)
Ah oui, très important. Ce qui veut dire que les pro s'ils veulent pouvoir le faire afficher devront écrire au support pour faire le changement... Je vais demander à l'équipe pour voir avec eux ce qui conviendrait le mieux ! 
En tout cas, n'hésite pas si tu as des questions dans ton exploration de l'app 😊

**Comment by arnaudpeich** [comment]
Suite à notre discussion sur Slack, on part donc sur un champ sur la table des campagnes. La raison principale étant qu'on peut vouloir activer/désactiver l'option selon les campagnes et que la déclaration d'un centre de vaccination doit passer par une validation d'un admin, donc ce serait compliqué d'ajouter un formulaire pour les modifier.

Ce que je propose : 
- Je pars de la PR #782 de @colinemarie pour rajouter le champ dans la nouvelle section "Informations pour les volontaires"
- Je rajoute un champ "numéro de téléphone à communiquer aux volontaires" **et non une case à cocher**
  - il sera pré-rempli avec le numéro indiqué à la création du centre de vaccination
  - il suffira de l'effacer pour ne pas le communiquer (j'ajouterai une indication pour le préciser)
  - ça règlera le problème des personnes qui ont mis un faux numéro au moment de l'inscription parce qu'ils n'ont pas compris à quoi servait le champ : ils pourront remettre le bon numéro à ce moment-là
  - ça permet aussi de mettre un numéro différent si ce n'est pas la même personne qui doit se charger de recevoir les volontaires d'une campagne sur l'autre

Est-ce que ça vous convient ?

**Comment by colinemarie** [comment]
L'idée est chouette, je mettrais juste un warning sur "il faut l'effacer pour ne pas le communiquer", à voir comment cela pourrait être le plus simple pour eux. D'après l'équipe supply, le comportement par défaut devrait être qu'ils ne communiquent pas leur téléphone.

**Comment by mininao** [comment]
Décision prise :
:one: On affiche toujours le numéro du centre aux volontaires ayant confirmé
    Ajout dans le mail de confirmation
    Ajout sur la page de match confirmé

:two: On l’explique à la création de campagne
    En dessous des détails d’accès, on écrit _Votre numéro 01XXXXXXXX sera communiqué aux volontaires ayant confirmé leur venue_
    On met un petit :information_source:  avec une tooltip qui dit _Mauvais numéro ? Contactez-nous à partenaires@covidliste.com_
    La tooltip s’affiche quand on passe sur le :information_source:  ou sur toute la phrase

:three: On l’explique à la création de centre
On rajoute la mention _:information_source: Ce numéro sera communiqué aux volontaires ayant confirmé leur RDV_
On remplace "_Numéro de téléphone fixe_" par "_Numéro de téléphone public_"
