### ISSUE TITLE
Éviter l'anonymisation des volontaires qui ont un match confirmé

### ISSUE THREAD

**Issue by rchampourlier** [hostolab/covidliste#802]
## Contexte / Problème

Contexte :

- Depuis ~1 semaine, lorsque l'utilisateur supprime son compte, le record est conservé anonymisé pour permettre un comptage correct des matches réalisés.
- Des volontaires suppriment leur compte après avoir confirmé un match.

Problèmes :

- L'envoi de l'email `send_confirmed_match_details.html.erb` lève une erreur et n'est donc pas envoyé
- Les informations sur le volontaire ne sont plus visibles sur la liste des volontaires matchés pour la campagne.

Erreur sur l'email dans AppSignal : https://appsignal.com/hostolab/sites/606a007b3b6e073e78117293/exceptions/incidents/454

## Proposition

[EDIT] Il semble que ce soit la suppression via le lien contenu dans les emails qui ne soit pas bloquée si le volontaire a un match confirmé.

- Supprimer le lien pour supprimer le compte dans les emails de match confirmé
- Vérifier que ce lien était le seul moyen non protégé de supprimer son compte avec un match confirmé

## Priorité (Requis)

`P1`: Urgent, à résoudre dans la journée :

- Concerne < 1% des nouveaux volontaires donc faible impact
- Mais pour les volontaires concernés, leurs infos ne sont pas visibles des centres de vaccination

**Comment by mathieuripert** [comment]
Je pense qu'on ne pourra pas empêcher les gens de cliquer sur le lien de suppression de compte envoyé via le match, même après un match confirmé, donc selon moi la solution est de faire une validation au niveau de l'action et ne pas permettre la suppression/anonymisation du compte tant que la campagne n'est pas terminée.
