### ISSUE TITLE
Créer l'envoi d'un SMS suite à un match confirmé

### ISSUE THREAD

**Issue by colinemarie** [hostolab/covidliste#807]
## Contexte / Problème

Lorsqu'un particulier confirme un match qui lui est proposé, il reçoit un email récapitulant son RDV et les informations (lieu de vaccination, nom/date de naissance communiquées...). 
Nous souhaitons qu'il puisse également recevoir un SMS lui confirmant son RDV et les infos essentielles.

## Proposition

- Réfléchir au contenu du SMS qui devra être fortement raccourci par rapport à l'email.
- Ajouter un job pour les SMS [ici](https://github.com/hostolab/covidliste/blob/main/app/controllers/matches_controller.rb#L18-36)

(Job actuel envoyant pour les SMS pour prévenir d'un match pour [inspiration](https://github.com/hostolab/covidliste/blob/main/app/jobs/send_match_sms_job.rb#L1-32)

## Priorité (Requis)

- `P2`: Moyennement urgent, à résoudre en 4 jours

**Comment by pducolin** [comment]
Mind if I take this task?

**Comment by carsso** [comment]
Autre inspiration #783 qui est la même chose mais pour le mail

**Comment by pducolin** [comment]
Pour le contenu de l'SMS je me suis inspirée aux SMS Doctolib

```
body = "RDV de vaccination confirmé pour #{match.campaign.starts_at.strftime('%A %d/%m')}"\
            "Entre #{match.campaign.starts_at.strftime('%Hh%M')} et #{match.campaign.ends_at.strftime('%Hh%M')}"
            ""\
            "#{match.vaccination_center.address} "\
            "Retrouvez plus d'info dans votre boite email"
```

Example
```
RDV de vaccination confirmé pour Dimanche 26/05
Entre 12h50 et 13h15

26 rue de la Cité 75020 Paris
Retrouvez plus d'info dans votre boite email
```

La syntax peut n'etre pas correct - c'est mon baby Ruby. Qu'est-ce que vous en pensez?

**Comment by mininao** [comment]
@pducolin Est-ce que tu penses qu'on peut essayer de faire en sorte que ça tienne en 1 sms pour la plupart des centres ? cf http://smscharactercount.com/#/counter

**Comment by pducolin** [comment]
Merci pour le lien! Avec l'example on est déjà à 148 chars. Je propose ce format plus raccourci 

```
RDV confirmé Dim 26/05
Entre 12h50 et 13h15

26 rue de la Cité 75020 Paris
Retrouvez plus d'info dans votre boite email
```

De cette façon on est a 123 chars, avec un peu plus de liberté pour l’adresse. Alternative, utiliser un short url vers google maps pour l’adresse - est-ce qu'on l'a déjà dans le data model d'un match? Advantage on a toujours la même string length

**Comment by carsso** [comment]
Perso je mettrai le nom du centre plutôt que l'adresse (pour la vérif a l'entre c'est mieux).
Et remettre le lien vers le match a la place de "plus d'info dans votre boite email"

**Comment by pducolin** [comment]
@carsso j'arrive pas à trouver le lien dans un match dans le model. Est-ce qu'il y a moyen de créer un url pour un match depuis son token id ?

**Comment by colinemarie** [comment]
Oui d'accord avec @carsso, j'écrirais quelque chose comme : 
`RDV confirmé Dim 26/05 entre 12h50 - 13h15
Pharmacie des Tournelles, Paris
Plus d'infos dans votre boite email`

Est-ce qu'on met `plus d'info dans votre boite email` ou le lien vers la page de match qui arriverait donc sur la page `confirmed`avec tous les détails ?

**Comment by carsso** [comment]
Plutôt le lien oui.
@pducolin Si t'es pas dans une view : https://github.com/hostolab/covidliste/blob/5d5464a60b9ee443a013039151eb49e510991e05/app/jobs/send_match_sms_job.rb#L50

**Comment by pducolin** [comment]
Est-ce que le url a une taille fixe? Pour etre safe je vais mettre un check pour le  nom du centre + ville pour avoir un `truncate` si trop long, et j'aurais besoin de connaitre plus ou moins la taille de l'url

**Comment by colinemarie** [comment]
L'url pour la page de match avec token, c'est par exemple `http://localhost:3000/m/nwCySp8WEtMqWbaCGKQk241c`
