### ISSUE TITLE
Proposition d'évolution : ajouter un peu de data à covidlist

### ISSUE THREAD

**Issue by max5962** [hostolab/covidliste#845]
Hello,

J'aimerais donner un coup de main à votre site et notamment dans la partie DATA.

Je pense que la carte covidList est intéressante mais quelques graphiques seraient intéressant : 
- évolution dans le temps des centre partenaires ( possible grace au champs "created_at" ) 
- évolution du nombre d'inscrit ( possible grâce au champs "created_at"

Cela ne semble pas trop complexe, une simple page avec une bonne requête groupé par "created_at" affiché avec googleChart ou DataViz.

Qu'en pensez-vous ? 

Merci :)

**Comment by mathieuripert** [comment]
> Hello,
> 
> J'aimerais donner un coup de main à votre site et notamment dans la partie DATA.
> 
> Je pense que la carte covidList est intéressante mais quelques graphiques seraient intéressant :
> 
> * évolution dans le temps des centre partenaires ( possible grace au champs "created_at" )
> * évolution du nombre d'inscrit ( possible grâce au champs "created_at"
> 
> Cela ne semble pas trop complexe, une simple page avec une bonne requête groupé par "created_at" affiché avec googleChart ou DataViz.
> 
> Qu'en pensez-vous ?
> 
> Merci :)

Merci @max5962 pour ta suggestion. Je te propose de nous rejoindre en tant que bénévoles https://www.covidliste.com/benevoles si tu souhaites nous aider sur cette partie. 
Je ferme l'issue en revanche car ce n'est pas a proprement parlé un bug/feature que l'on souhaite rajouter au produit
