### ISSUE TITLE
Empêcher les erreurs liées à une heure locale incorrecte sur l'ordinateur des centres de vaccination

### ISSUE THREAD

**Issue by mininao** [hostolab/covidliste#856]
## Contexte / Problème

Il semblerait que certains centres de vaccination puissent créer des campagnes dans le passée si leur ordinateur n'est pas dans la bonne timezone. [Exemple](https://covidliste.slack.com/archives/C01TKMUTP4M/p1621696122362100) 

## Proposition

- Vérifier que l'heure locale est correcte ? Vérifier l'heure côté serveur cc @EmCousin ?

**Comment by EmCousin** [comment]
@mininao je n'ai pas accès au canal Slack vers lequel ton lien redirige. Peux-tu m'y ajouter ?
Pour le reste, il faudrait effectivement vérifier l'heure locale des deux côtés. Je devrais avoir un peu de temps pour m'en occuper cet après midi

**Comment by mininao** [comment]
Déso j'ai pas vu ton com @EmCousin ! Je t'ai ajouté au channel, merci 😄 !
