### ISSUE TITLE
Opt out of Google’s FLoC User Tracking in Rails

### ISSUE THREAD

**Issue by navidemad** [hostolab/covidliste#872]
## Contexte / Problème

Google has recently built user tracking directly into Chrome. This new technology is named Federated Learning of Cohorts (shortened to FLoC).

Source: https://andycroll.com/ruby/opt-out-of-google-floc-tracking-in-rails/

**Comment by adrienpoly** [comment]
FYI 

https://github.com/hostolab/covidliste/pull/423

**Comment by navidemad** [comment]
Autant pour moi je l'avais vu passer sur master, j'ai vu ça sur mon feed twitter 😄
