### ISSUE TITLE
Mail de validation de compte: lien incorrect dans la version HTML

### ISSUE THREAD

**Issue by FRIESyourAnalytics** [hostolab/covidliste#878]
## Contexte / Problème

Ce 26 mai, la version HTML du mail "Validez votre inscription sur Covidliste" contient 2 liens différents pour la validation, l'un d'eux n'est pas fonctionnel 

## Proposition

Mettre la bonne valeur dans les deux liens

## Priorité (Requis)

Ajouter un label `Priorité`

- `P2`: Moyennement urgent, à résoudre en 4 jours
L'un des 2 liens fonctionne, mais pas idéal quand même

En détail : Lien vers "https://r.sib.covidliste.com/" mais ce site n'a pas de résolution DNS 

```html
<br>
    Finalisez votre inscription en cliquant sur le lien suivant (valide pen=
dant 24 heures) :
    <br>
    <strong>
      <a href=3D"https://r.sib.covidliste.com/tr/cl/09zkhTT_truc_bidule_chouette">Valider mon inscription</a>
    </strong>
  </p>

  <p>
    <strong>Si le lien ne fonctionne pas</strong>, copiez et collez l=E2=80=
=99adresse suivante dans votre navigateur :
    <br>
    https://www.covidliste.com/users/confirmation?confirmation_token=_truc_bidule_chouette
  </p>
```

**Comment by FRIESyourAnalytics** [comment]
La version texte seul du message comprend 2 liens identiques

`Finalisez votre inscription en cliquant sur le lien suivant

(valide pendant 24 heures) :



Valider mon inscription=20

( https://www.covidliste.com/users/confirmation?confirmation_token=3Dax-iyr=
7xo_AACz4QNDDn )





Si le lien ne fonctionne pas, copiez et collez l=E2=80=99adresse

suivante dans votre navigateur :



https://www.covidliste.com/users/confirmation?confirmation_token=3Dax-iyr7x=
o_AACz4QNDDn
`

**Comment by GuillaumeWrobel** [comment]
Ola @FRIESyourAnalytics ,

Je me suis permis d'éditer ton message en formattant le code avec les 3 ticks pour les blocs de code, et en réécrivant les token de tes liens pour ne pas dévoiler de tokens privés.

Quant au problème, Sendinblue doit réécrire les liens pour faire du suivi de clics (cf « [Pourquoi l'URL de mes liens est-il différent de ce que j'ai choisi?](https://help.sendinblue.com/hc/fr/articles/209421325-Pourquoi-l-URL-de-mes-liens-est-il-diff%C3%A9rent-de-ce-que-j-ai-choisi-) »)

Quelle page as-tu eue quand tu as cliqué sur ce lien réécrit ?

**Comment by FRIESyourAnalytics** [comment]
Merci @GuillaumeWrobel, et désolé, je ne suis pas très habile avec cet "éditeur" de texte

J'ai eu une page d'erreur DNS de Chrome

Elle a fini par se recharger un peu plus tard avec succès

J'utilise les DNS de Google : 8.8.8.8 et 8.8.4.4

c'est en place depuis peu ce mécanisme ? ça n'était pas encore bien propagé ?

**Comment by carsso** [comment]
On a eu des soucis de DNS sur certains des liens, particulièrement pour les résolveurs qui font la vérification DNSSEC.
Normalement ce problème là est corrigé.
