### ISSUE TITLE
Investiguer et remédier les mails lents

### ISSUE THREAD

**Issue by mininao** [hostolab/covidliste#883]
## Contexte / Problème

* De nombreux mails (de confirmation de RDV, de lien de connexion) mettent longtemps à parvenir à leurs destinataires, parfois plus d'une heure

Slack threads : [1](https://covidliste.slack.com/archives/C01T5RYDRAS/p1622041527254400), [2](https://covidliste.slack.com/archives/C01T48BHRCL/p1621963102116100)
cc @carsso @mathieuripert 

## Proposition

Je ne sais pas encore !

**Comment by GuillaumeWrobel** [comment]
Je parie que c'est du côté de Sendinblue qui fait du throttle ... dépasse-t-on le quota horaire de mails ? Que dit leur support ?

**Comment by adrienpoly** [comment]
Avons nous les stats sur les jobs sidekiq ? Est il possible que lorsque les centres lancent les campagnes (typiquement en fin de journée je suppose) tout d'un coup il y a beaucoup de job et du coup les mails restent bloqués le temps que nos workers absorbent le pic d'activité ?

Sinon oui chez SIB on a eu aussi des PB de throttle mais plus sur de l'envoie de campagne et de flot d'automation. J'ai pas souvenir d'avoir eu de PB sur du transactionnel.

**Comment by adrienpoly** [comment]
Bon j'ai creusé un peu plus et en l'état les emails Devise ne passent pas par un background job mais ils sont envoyés directement dans la transaction Web. Du coup pour moi cela supprime complètement l'hypothèse d'une surcharge des workers Sidekiq et je penche plutôt pour un délai coté SIB.

PS : si on voulait passer les envoies des mails devise en Async il y a plus d'information ici sur la method à override dans le model User/Partner
https://github.com/heartcombo/devise#activejob-integration
Cela est peut être une autre issue à ouvrir pour discuter de la pertinence ou non d'avoir les mails en background

**Comment by mathieuripert** [comment]
@adrienpoly c'est que je me dis aussi. Envoyer les emails via sidekiq permettrait de faire un peu throttle de notre cote ce qui pourrait eviter de la surchage cote SIB.
https://github.com/hostolab/covidliste/pull/892 est ce que selon toi ca suffit ? Ou alors pour les emails devise il faut aussi suivre la reco https://github.com/heartcombo/devise#activejob-integration
