### ISSUE TITLE
Demander la raison de suppression de compte

### ISSUE THREAD

**Issue by mathieuripert** [hostolab/covidliste#907]
## Contexte / Problème

Tracker la raison pour laquelle les volontaires suppriment le compte Covidliste.
Essentiellement, on souhaite recueuillir cette information a des fins statistiques pour connaitre le nombre de personnes "vaccinees" grace a Covidliste.

## Proposition

Raisons:

- J'ai trouve un rdv grace a Covidliste
- Je ne suis plus interesse
- Ignorer

![Capture d’écran 2021-05-31 à 10 21 42](https://user-images.githubusercontent.com/128908/120171190-0e441c80-c202-11eb-8f81-f1516c76c8d0.png)

**Comment by mathieuripert** [comment]
Details:

- [ ] nouvelle colonne `anonymized_reason` (enum)
- [ ] modification page de suppression pour demander la raison
- [ ] pour les anonymisations automatiques suites aux matches confirmes, choisir la raison 2 automatiquement
- [ ] ajouter FAQ item pour expliquer pourquoi on demande cette info
- [ ] checker avec legal que cette donnee n'est pas une donnee de sante sachant qu'elle n'est pas relie a une donnee perso (le compte est anonymise)

**Comment by mathieuripert** [comment]
@Florto est ce que tu peux m'aider a confirmer qu'en faisant ca, ce n'est pas considere comme une donnee de sante ? (desole j'ai perdu les accents sur mon clavier)

**Comment by Florto** [comment]
On en a discuté sur slack.

Tant qu’on demande pas si le user a bien été vacciné, pour moi c’est bon.
Mais j’aurais bien ajouté une petite checkbox ou au moins un laïus informatif à base de « cette information ne sera pas associée à votre compte qui est sur le point d’être supprimé, mais stocké de façon entièrement anonyme. Si vous refusez de communiquer cette information, cliquez sur ignorer. »

**Comment by ardjo-s** [comment]
@Florto si on met un petit texte explicatif sous les 3 options c'est suffisant non ? on a vraiment besoin de cette info et rajouter une checkbox c'est alourdir le flow pour rien à mon sens..

**Comment by Florto** [comment]
Mets le texte oui :)

>

**Comment by ardjo-s** [comment]
@Florto  "Covidliste demande cette information afin de s'assurer que vous avez pu être mise en relation. Cette information est anonymisée." C'est bon pour toi ? 
![Capture d’écran 2021-06-01 à 10 36 54](https://user-images.githubusercontent.com/10088552/120293236-55471600-c2c5-11eb-80ba-36ca39d214bb.png)

En vrai @mathieuripert si l'info n'est même pas rattachée à un compte on pourrait ne pas la mettre non ?

**Comment by Florto** [comment]
Je pense qu'il est essentiel de donner toutes les informations, ce qui ne me semble pas le cas dans ta nouvelle proposition.

**Comment by ardjo-s** [comment]
Il manque quoi ?

**Comment by Florto** [comment]
Anonymisé != pas associé au compte.

Que le compte sera bien supprimé.

Que en choisissant ignorer ils ne seront pas obligé de répondre à la question.

**Comment by ardjo-s** [comment]
"Covidliste demande cette information afin de s'assurer que vous avez pu être mise en relation. Cette information n'est pas associée à votre compte."
Pour tes autres points c'est obvious à mon avis. Tu en penses quoi ?
