### ISSUE TITLE
Cleaning - Relance puis suppression des comptes n'ayant jamais matché

### ISSUE THREAD

**Issue by Damienre** [hostolab/covidliste#949]
## Contexte / Problème

De nombreux comptes se sont vu proposés des rdv et n'ont jamais confirmé leur match, ce qui peut "vampiriser" la demande active.

## Proposition

Mise en place d'un mail pour se déclarer "toujours actif" pour les compte s'étant vu proposer plus de X matchs sans n'avoir jamais confirmé. 
X étant paramétrable, commencer avec X = 20.
Si aucun clic sur le bouton "Restez alerté", alors le compte est anonymisé 48h plus tard.

Lien vers le wording : 
https://covidliste.slite.com/app/channels/Qw04YcNl2c/notes/d3hYzhuugy

Lien figma:
https://www.figma.com/file/gRlA4jL13fJo6NwCuZCgyw/Mails-volontaire?node-id=255%3A0

(Prendre le wording slite et pas figma)

## Priorité (Requis)

Ajouter un label `Priorité`

- `P2`: Moyennement urgent, à résoudre en 4 jours

**Comment by navidemad** [comment]
Ca fait pas doublon avec ce mail déjà ?

On a déjà une tache qui passe qui va envoyer ce mail quand il y a au moins 2 refus ou 2 matches non répondues :

<img width="789" alt="Screenshot 2021-07-01 at 00 43 00" src="https://user-images.githubusercontent.com/6686865/124040554-676fbd80-da05-11eb-8430-7cf33bd56d2a.png">

**Comment by mininao** [comment]
Résolu par #1001
