### ISSUE TITLE
Update de la FAQ

### ISSUE THREAD

**Issue by peiofour** [hostolab/covidliste#95]
Mise à jour de la FAQ avec les nouvelles/reponses.
La liste : https://docs.google.com/spreadsheets/d/1SX_w4CbAzSwd1jAz-PBHN85oi7riKVywf8FREzYOWaI/edit#gid=0

Issue à ne pas fermer, la page risque d'être mise à jour fréquemment

**Comment by rchampourlier** [comment]
Je pense que cette issue n'est plus d'actualité, il me semble que les FAQs du document attaché sont déjà sur le site et que s'il faut les faire évoluer ça peut directement être fait par une PR si besoin.
